server {
    listen 443 ssl http2;
    server_name spectra.devops00.com;

    # 单 IP 最大并发
    limit_conn conn_limit 20;

    # 单 IP 请求速率
    limit_req zone=req_limit burst=20 nodelay;

    ssl_certificate     /etc/letsencrypt/live/devops00.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devops00.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # 强制 HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # 启用 HTTP/2
    large_client_header_buffers 4 32k;

    # 限制请求大小,限制为10M
    client_max_body_size 10M;

    # ===== 前端 =====
    root /usr/share/nginx/html/spectra;
    index index.html;

    # 禁 WP 探测 / 扫描
    location ~* ^/(wp-admin|wp-login|xmlrpc\.php) {
        return 444;
    }

     # 禁止访问敏感文件
    location ~* \.(git|env|ini|log|sh|bashrc|htaccess|htpasswd|passwd)$ {
        deny all;
        return 403;
    }

    # JS 文件处理
    location ~* \.js$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable, max-age=31536000";
    }

    # CSS 文件处理
    location ~* \.css$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable, max-age=31536000";
    }

    # favicon.ico 文件处理
    location = /favicon.ico {
        try_files $uri =404;
        access_log off;
        expires 30d;
    }

    # 处理所有其他静态资源，通常包括 JS 和 CSS 文件
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp|ttf|woff|woff2|eot)$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable, max-age=31536000";
    }


    # ===== API =====
    location /api/ {
        proxy_pass http://spectra-admin:8888;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 120s;
        proxy_send_timeout 60s;
    }

    # ===== SPA fallback =====
    location / {
        # 禁止其他 HTTP 方法（仅允许 GET、POST 和 HEAD）
        if ($request_method !~ ^(GET|POST|HEAD)$ ) {
            return 444;
        }

        # 禁止常见扫描工具和恶意 User-Agent
        if ($http_user_agent ~* "curl|wget|python|libwww|HTTrack|Nmap|scanner|masscan") {
            return 403;
        }

        # 禁止 SQL 注入攻击
        set $blocked 0;
        if ($query_string ~* "union.*select.*\(") {
            set $blocked 1;
        }
        if ($query_string ~* "select.*from.*information_schema.tables") {
            set $blocked 1;
        }
        if ($blocked) {
            return 403;
        }

        # Vue SPA 路由处理
        try_files $uri $uri/ /index.html;
    }

}