# 自己项目的配置
spectra:
  # 系统配置
  system:
    # 基础文件夹位置,后续日志;文件上传保存等位置都要以这个位置为基础
    base-dir: files
  # 用户相关(admin123)
  user:
    default-password: ${DEFAULT_PASSWORD}
  # 文件相关
  file:
    # 文件上传配置
    upload:
      # 上传文件的位置
      upload-dir: ${spectra.system.base-dir}/uploads
      # 上传文件的位置(临时存储位置)
      upload-temp-dir: ${spectra.system.base-dir}/temp
  # 验证码相关
  kaptcha:
    type: math
    verify: true
# spring 配置
spring:
  config:
    # 导入druid的数据库配置
    import: classpath:application-db-druid.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true
  # 应用名称
  application:
    name: spectra-admin
  # redis
  data:
    redis:
      url: redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      timeout: 10s
      connect-timeout: 5s
      lettuce:
        pool:
          enabled: true
          max-idle: 10
          min-idle: 2
          max-active: 20
          max-wait: 5000ms
        shutdown-timeout: 100ms
  # 关闭他自带的用户
  security:
    user:
      name:
      password:
  # 缓存
  cache:
    type: redis
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.devops00.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      # 开发过程中,不使用逻辑删除
      # logic-delete-field: deleted
      # logic-not-delete-value: "null"
      # logic-delete-value: "now()"
      # schema: SPECTRA
      # mp相关代码会用到
      schema: spectra_core
  # 注入到xml的变量
  configuration-properties:
    schema: spectra_core
# 日志配置
logging:
  group:
    spectra: >-
      com.devops00.spectra
    other: >-
      com.ulisesbocchio.jasyptspringboot.configuration
  level:
    root: info
    other: error
    spectra: debug
# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# 工作流配置
flowable:
  # 数据库确定
  database-schema: spectra_workflow
  database-schema-update: true
  jpa-enabled: false
  # 流程定义
  process-definition-location-prefix: classpath*:/processes/
  async-executor-activate: true
  history-level: full
  # 下面是所有可选模块,都用不到
  # 事件注册模块
  eventregistry:
    enabled: false
  # 身份管理引擎
  idm:
    enabled: false
  # Flowable 的“应用元模型”
  app:
    enabled: false
  # 决策模型引擎
  dmn:
    enabled: false
  # 案例管理引擎
  cmmn:
    enabled: false
# XSS防范
mica:
  xss:
    # 是否开启
    enabled: true
    # 拦截的
    path-patterns: /**
    # 放行的
    path-exclude-patterns:
