# 自己项目的配置
spectra:
  # 系统配置
  system:
    # 基础文件夹位置,后续日志;文件上传保存等位置都要以这个位置为基础
    base-dir: files
  # 用户相关(admin123)
  user:
    default-password: ${DEFAULT_PASSWORD}
  # 验证码相关
  kaptcha:
    type: math
    verify: false
# 服务器配置
server:
  port: ${SERVER_PORT:80}
  ssl:
    key-store: ${spectra.system.base-dir}/ssl/keystore.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: ${SSL_TYPE}
    key-alias: ${SSL_ALIAS}
  servlet:
    context-path: /api
    session:
      cookie:
        name: JSESSIONID
        path: /
        same-site: none
        secure: true
        http-only: true
# spring 配置
spring:
  # servlet
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  # 虚拟线程
  threads:
    virtual:
      enabled: true
  # 应用名称
  application:
    name: spectra-admin
  # 数据配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 这部分为URL?后面的参数. 会自动拼接上去
      data-source-properties:
        # 当前SCHEMA
        currentSchema: public
        # 控制Java String参数在SQL中的绑定类型 unspecified=让 PostgreSQL 自行推断类型
        stringtype: unspecified
        # 启用 批量 INSERT 重写优化
        reWriteBatchedInserts: true
        # 允许 JDBC Driver 使用 二进制协议 传输数据
        binaryTransfer: true
        # 开启TCP层KeepAlive探测
        tcpKeepAlive: true
        # 数据库建立TCP连接的超时时间（秒）
        connectTimeout: 10
        # 数据库读操作的Socket超时（秒）
        socketTimeout: 60
        # 应用名称
        ApplicationName: ${spring.application.name}
        # JDBC层面的登录超时（秒）
        loginTimeout: 10
        # 明确SSL行为，避免 Driver 自动探测浪费时间
        sslmode: disable
        # 控制Server-side Prepared Statement启用阈值
        prepareThreshold: 5
  # redis
  data:
    redis:
      url: redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      timeout: 10s
      connect-timeout: 5s
      lettuce:
        pool:
          enabled: true
          max-idle: 10
          min-idle: 2
          max-active: 20
          max-wait: 5000ms
        shutdown-timeout: 100ms
  # 关闭他自带的用户
  security:
    user:
      name:
      password:
  # 缓存
  cache:
    type: redis
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.devops00.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      # 开发过程中,不使用逻辑删除
      # logic-delete-field: deleted
      # logic-not-delete-value: "null"
      # logic-delete-value: "now()"
      # schema: SPECTRA
      # mp相关代码会用到
      schema: spectra_core
  # 注入到xml的变量
  configuration-properties:
    schema: spectra_core
# 日志配置
logging:
  group:
    spectra: >-
      com.devops00.spectra
    other: >-
      com.ulisesbocchio.jasyptspringboot.configuration
  level:
    root: info
    other: error
    spectra: debug
# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

