-- 重建用户表

DROP TABLE IF EXISTS "SPECTRA"."T_SYS_ACCOUNT2";
CREATE TABLE "SPECTRA"."T_SYS_ACCOUNT"
(
    ID         BIGINT       NOT NULL,
    USERNAME   VARCHAR(20)  NOT NULL,
    PASSWORD   VARCHAR(60)  NOT NULL,
    USER_ID    BIGINT       NOT NULL,
    TYPE       INT          NOT NULL,
    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_BY BIGINT,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    DELETED    TIMESTAMP(6)
)