/*
 *  Copyright 2018-2026 yangxj96
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

-- Quartz 2.5.2 PostgreSQL JobStore 的完整表结构，所有表固定在独立 schema。
CREATE SCHEMA IF NOT EXISTS spectra_quartz;

CREATE TABLE spectra_quartz.QRTZ_JOB_DETAILS
(
    SCHED_NAME        VARCHAR(120) NOT NULL,
    JOB_NAME          VARCHAR(200) NOT NULL,
    JOB_GROUP         VARCHAR(200) NOT NULL,
    DESCRIPTION       VARCHAR(250),
    JOB_CLASS_NAME    VARCHAR(250) NOT NULL,
    IS_DURABLE        BOOLEAN      NOT NULL,
    IS_NONCONCURRENT  BOOLEAN      NOT NULL,
    IS_UPDATE_DATA    BOOLEAN      NOT NULL,
    REQUESTS_RECOVERY BOOLEAN      NOT NULL,
    JOB_DATA          BYTEA,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_TRIGGERS
(
    SCHED_NAME     VARCHAR(120) NOT NULL,
    TRIGGER_NAME   VARCHAR(200) NOT NULL,
    TRIGGER_GROUP  VARCHAR(200) NOT NULL,
    JOB_NAME       VARCHAR(200) NOT NULL,
    JOB_GROUP      VARCHAR(200) NOT NULL,
    DESCRIPTION    VARCHAR(250),
    NEXT_FIRE_TIME BIGINT,
    PREV_FIRE_TIME BIGINT,
    PRIORITY       INTEGER,
    TRIGGER_STATE  VARCHAR(16)  NOT NULL,
    TRIGGER_TYPE   VARCHAR(8)   NOT NULL,
    START_TIME     BIGINT       NOT NULL,
    END_TIME       BIGINT,
    CALENDAR_NAME  VARCHAR(200),
    MISFIRE_INSTR  SMALLINT,
    JOB_DATA       BYTEA,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES spectra_quartz.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_SIMPLE_TRIGGERS
(
    SCHED_NAME      VARCHAR(120) NOT NULL,
    TRIGGER_NAME    VARCHAR(200) NOT NULL,
    TRIGGER_GROUP   VARCHAR(200) NOT NULL,
    REPEAT_COUNT    BIGINT       NOT NULL,
    REPEAT_INTERVAL BIGINT       NOT NULL,
    TIMES_TRIGGERED BIGINT       NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_CRON_TRIGGERS
(
    SCHED_NAME     VARCHAR(120) NOT NULL,
    TRIGGER_NAME   VARCHAR(200) NOT NULL,
    TRIGGER_GROUP  VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(120) NOT NULL,
    TIME_ZONE_ID   VARCHAR(80),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_SIMPROP_TRIGGERS
(
    SCHED_NAME    VARCHAR(120)   NOT NULL,
    TRIGGER_NAME  VARCHAR(200)   NOT NULL,
    TRIGGER_GROUP VARCHAR(200)   NOT NULL,
    STR_PROP_1    VARCHAR(512),
    STR_PROP_2    VARCHAR(512),
    STR_PROP_3    VARCHAR(512),
    INT_PROP_1    INTEGER,
    INT_PROP_2    INTEGER,
    LONG_PROP_1   BIGINT,
    LONG_PROP_2   BIGINT,
    DEC_PROP_1    NUMERIC(13, 4),
    DEC_PROP_2    NUMERIC(13, 4),
    BOOL_PROP_1   BOOLEAN,
    BOOL_PROP_2   BOOLEAN,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_BLOB_TRIGGERS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_NAME  VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA     BYTEA,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_CALENDARS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR      BYTEA        NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

CREATE TABLE spectra_quartz.QRTZ_PAUSED_TRIGGER_GRPS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

CREATE TABLE spectra_quartz.QRTZ_FIRED_TRIGGERS
(
    SCHED_NAME        VARCHAR(120) NOT NULL,
    ENTRY_ID          VARCHAR(95)  NOT NULL,
    TRIGGER_NAME      VARCHAR(200) NOT NULL,
    TRIGGER_GROUP     VARCHAR(200) NOT NULL,
    INSTANCE_NAME     VARCHAR(200) NOT NULL,
    FIRED_TIME        BIGINT       NOT NULL,
    SCHED_TIME        BIGINT       NOT NULL,
    PRIORITY          INTEGER      NOT NULL,
    STATE             VARCHAR(16)  NOT NULL,
    JOB_NAME          VARCHAR(200),
    JOB_GROUP         VARCHAR(200),
    IS_NONCONCURRENT  BOOLEAN,
    REQUESTS_RECOVERY BOOLEAN,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE spectra_quartz.QRTZ_SCHEDULER_STATE
(
    SCHED_NAME        VARCHAR(120) NOT NULL,
    INSTANCE_NAME     VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT       NOT NULL,
    CHECKIN_INTERVAL  BIGINT       NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

CREATE TABLE spectra_quartz.QRTZ_LOCKS
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME  VARCHAR(40)  NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY
    ON spectra_quartz.QRTZ_JOB_DETAILS (SCHED_NAME, REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_J_GRP
    ON spectra_quartz.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_J
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_JG
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_C
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, CALENDAR_NAME);
CREATE INDEX IDX_QRTZ_T_G
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_T_STATE
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_STATE
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_G_STATE
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE
    ON spectra_quartz.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP
    ON spectra_quartz.QRTZ_TRIGGERS
        (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME
    ON spectra_quartz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME);
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY
    ON spectra_quartz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_FT_J_G
    ON spectra_quartz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_JG
    ON spectra_quartz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_T_G
    ON spectra_quartz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TG
    ON spectra_quartz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);

COMMENT ON TABLE spectra_quartz.QRTZ_JOB_DETAILS IS 'Quartz JobDetail 定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.JOB_NAME IS 'Job 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.JOB_GROUP IS 'Job 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.DESCRIPTION IS 'Job 描述';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.JOB_CLASS_NAME IS 'Job 实现类名，由代码白名单提供';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.IS_DURABLE IS 'JobDetail 是否持久化保留';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.IS_NONCONCURRENT IS '是否禁止同一 Job 并发执行';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.IS_UPDATE_DATA IS '执行时是否更新 JobDataMap';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.REQUESTS_RECOVERY IS '节点故障后是否请求恢复执行';
COMMENT ON COLUMN spectra_quartz.QRTZ_JOB_DETAILS.JOB_DATA IS 'Quartz 序列化的非敏感 JobDataMap';

COMMENT ON TABLE spectra_quartz.QRTZ_TRIGGERS IS 'Quartz Trigger 基础定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.TRIGGER_NAME IS 'Trigger 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.TRIGGER_GROUP IS 'Trigger 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.JOB_NAME IS '关联 Job 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.JOB_GROUP IS '关联 Job 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.DESCRIPTION IS 'Trigger 描述';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.NEXT_FIRE_TIME IS '下一次触发时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.PREV_FIRE_TIME IS '上一次触发时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.PRIORITY IS '触发优先级';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.TRIGGER_STATE IS 'Trigger 当前状态';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.TRIGGER_TYPE IS 'Trigger 类型';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.START_TIME IS 'Trigger 生效时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.END_TIME IS 'Trigger 失效时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.CALENDAR_NAME IS '关联 Quartz Calendar 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.MISFIRE_INSTR IS '错过触发的 Quartz 原生策略编码';
COMMENT ON COLUMN spectra_quartz.QRTZ_TRIGGERS.JOB_DATA IS 'Trigger 序列化的非敏感 JobDataMap';

COMMENT ON TABLE spectra_quartz.QRTZ_SIMPLE_TRIGGERS IS 'Quartz SimpleTrigger 扩展定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPLE_TRIGGERS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME IS 'Trigger 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP IS 'Trigger 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT IS '重复次数，负数表示无限重复';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL IS '两次触发之间的间隔毫秒数';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED IS '已经触发的次数';

COMMENT ON TABLE spectra_quartz.QRTZ_CRON_TRIGGERS IS 'Quartz CronTrigger 扩展定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_CRON_TRIGGERS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_CRON_TRIGGERS.TRIGGER_NAME IS 'Trigger 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_CRON_TRIGGERS.TRIGGER_GROUP IS 'Trigger 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_CRON_TRIGGERS.CRON_EXPRESSION IS 'Quartz Cron 表达式';
COMMENT ON COLUMN spectra_quartz.QRTZ_CRON_TRIGGERS.TIME_ZONE_ID IS 'Cron 表达式使用的 IANA 时区';

COMMENT ON TABLE spectra_quartz.QRTZ_SIMPROP_TRIGGERS IS 'Quartz SimplePropertiesTrigger 扩展定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME IS 'Trigger 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP IS 'Trigger 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.STR_PROP_1 IS '字符串属性一';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.STR_PROP_2 IS '字符串属性二';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.STR_PROP_3 IS '字符串属性三';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.INT_PROP_1 IS '整数属性一';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.INT_PROP_2 IS '整数属性二';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_1 IS '长整数属性一';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_2 IS '长整数属性二';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_1 IS '小数属性一';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_2 IS '小数属性二';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_1 IS '布尔属性一';
COMMENT ON COLUMN spectra_quartz.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_2 IS '布尔属性二';

COMMENT ON TABLE spectra_quartz.QRTZ_BLOB_TRIGGERS IS 'Quartz 自定义 BlobTrigger 扩展定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_BLOB_TRIGGERS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME IS 'Trigger 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP IS 'Trigger 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_BLOB_TRIGGERS.BLOB_DATA IS 'Trigger 序列化扩展数据';

COMMENT ON TABLE spectra_quartz.QRTZ_CALENDARS IS 'Quartz Calendar 定义表';
COMMENT ON COLUMN spectra_quartz.QRTZ_CALENDARS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_CALENDARS.CALENDAR_NAME IS 'Calendar 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_CALENDARS.CALENDAR IS 'Calendar 序列化定义';

COMMENT ON TABLE spectra_quartz.QRTZ_PAUSED_TRIGGER_GRPS IS 'Quartz 暂停 Trigger 分组表';
COMMENT ON COLUMN spectra_quartz.QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP IS '暂停的 Trigger 分组';

COMMENT ON TABLE spectra_quartz.QRTZ_FIRED_TRIGGERS IS 'Quartz 已触发 Trigger 运行实例表';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.ENTRY_ID IS '触发实例唯一入口标识';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.TRIGGER_NAME IS 'Trigger 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP IS 'Trigger 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.INSTANCE_NAME IS '执行该触发的 Scheduler 实例';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.FIRED_TIME IS '实际触发时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.SCHED_TIME IS '计划触发时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.PRIORITY IS '触发优先级';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.STATE IS '触发实例状态';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.JOB_NAME IS '关联 Job 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.JOB_GROUP IS '关联 Job 分组';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT IS '关联 Job 是否禁止并发';
COMMENT ON COLUMN spectra_quartz.QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY IS '节点故障后是否请求恢复';

COMMENT ON TABLE spectra_quartz.QRTZ_SCHEDULER_STATE IS 'Quartz 集群 Scheduler 实例心跳表';
COMMENT ON COLUMN spectra_quartz.QRTZ_SCHEDULER_STATE.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_SCHEDULER_STATE.INSTANCE_NAME IS 'Scheduler 实例名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME IS '最近一次集群心跳时间的 Unix 毫秒值';
COMMENT ON COLUMN spectra_quartz.QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL IS '集群心跳间隔毫秒数';

COMMENT ON TABLE spectra_quartz.QRTZ_LOCKS IS 'Quartz 集群数据库锁表';
COMMENT ON COLUMN spectra_quartz.QRTZ_LOCKS.SCHED_NAME IS 'Quartz Scheduler 名称';
COMMENT ON COLUMN spectra_quartz.QRTZ_LOCKS.LOCK_NAME IS 'Quartz 锁名称';
