-- Normalize the deployed security schema without copying or deleting data.
-- Existing V1-V17 migrations are intentionally immutable; this migration is
-- the compatibility bridge for databases that already applied those versions.

-- Tables
ALTER TABLE spectra_security.permission RENAME TO sec_permission;
ALTER TABLE spectra_security.role RENAME TO sec_role;
ALTER TABLE spectra_security.role_permission RENAME TO sec_role_permission;
ALTER TABLE spectra_security.role_grantable_permission RENAME TO sec_role_grantable_permission;
ALTER TABLE spectra_security.role_assignment RENAME TO sec_role_assignment;
ALTER TABLE spectra_security.authorization_scope RENAME TO sec_authorization_scope;
ALTER TABLE spectra_security.assignment_permission_boundary RENAME TO sec_assignment_permission_boundary;
ALTER TABLE spectra_security.assignment_grant_boundary RENAME TO sec_assignment_grant_boundary;
ALTER TABLE spectra_security.scope_rule RENAME TO sec_scope_rule;
ALTER TABLE spectra_security.authentication_identity RENAME TO sec_authentication_identity;
ALTER TABLE spectra_security.password_credential RENAME TO sec_password_credential;
ALTER TABLE spectra_security.security_client RENAME TO sec_security_client;
ALTER TABLE spectra_security.authentication_method RENAME TO sec_authentication_method;
ALTER TABLE spectra_security.client_auth_method RENAME TO sec_client_auth_method;
ALTER TABLE spectra_security.session_policy RENAME TO sec_session_policy;
ALTER TABLE spectra_security.password_policy RENAME TO sec_password_policy;
ALTER TABLE spectra_security.mfa_enrollment RENAME TO sec_mfa_enrollment;
ALTER TABLE spectra_security.totp_credential RENAME TO sec_totp_credential;
ALTER TABLE spectra_security.recovery_code RENAME TO sec_recovery_code;
ALTER TABLE spectra_security.root_policy RENAME TO sec_root_policy;
ALTER TABLE spectra_security.security_audit_event RENAME TO sec_security_audit_event;
ALTER TABLE spectra_security.security_audit_event_default RENAME TO sec_security_audit_event_default;
ALTER TABLE spectra_security.security_audit_retention_policy RENAME TO sec_security_audit_retention_policy;
ALTER TABLE spectra_security.security_audit_archive_manifest RENAME TO sec_security_audit_archive_manifest;
ALTER TABLE spectra_security.security_change_outbox RENAME TO sec_security_change_outbox;
ALTER TABLE spectra_security.role_menu RENAME TO sec_role_menu;

-- Primary keys, foreign keys, checks and unique constraints
ALTER TABLE spectra_security.sec_permission RENAME CONSTRAINT permission_pkey TO pk_sec_permission;
ALTER TABLE spectra_security.sec_permission RENAME CONSTRAINT ck_security_permission_code TO ck_sec_permission_code;
ALTER TABLE spectra_security.sec_permission RENAME CONSTRAINT ck_security_permission_state TO ck_sec_permission_state;
ALTER TABLE spectra_security.sec_permission RENAME CONSTRAINT uk_security_permission_code TO uk_sec_permission_code;

ALTER TABLE spectra_security.sec_role RENAME CONSTRAINT role_pkey TO pk_sec_role;
ALTER TABLE spectra_security.sec_role RENAME CONSTRAINT ck_security_role_code TO ck_sec_role_code;
ALTER TABLE spectra_security.sec_role RENAME CONSTRAINT ck_security_role_authority TO ck_sec_role_authority;
ALTER TABLE spectra_security.sec_role RENAME CONSTRAINT ck_security_role_state TO ck_sec_role_state;
ALTER TABLE spectra_security.sec_role RENAME CONSTRAINT ck_security_role_kind TO ck_sec_role_kind;
ALTER TABLE spectra_security.sec_role RENAME CONSTRAINT uk_security_role_code TO uk_sec_role_code;

ALTER TABLE spectra_security.sec_role_permission RENAME CONSTRAINT role_permission_pkey TO pk_sec_role_permission;
ALTER TABLE spectra_security.sec_role_permission RENAME CONSTRAINT role_permission_role_id_fkey TO fk_sec_role_permission_role_id;
ALTER TABLE spectra_security.sec_role_permission RENAME CONSTRAINT role_permission_permission_id_fkey TO fk_sec_role_permission_permission_id;

ALTER TABLE spectra_security.sec_role_grantable_permission RENAME CONSTRAINT role_grantable_permission_pkey TO pk_sec_role_grantable_permission;
ALTER TABLE spectra_security.sec_role_grantable_permission RENAME CONSTRAINT role_grantable_permission_role_id_fkey TO fk_sec_role_grantable_permission_role_id;
ALTER TABLE spectra_security.sec_role_grantable_permission RENAME CONSTRAINT role_grantable_permission_permission_id_fkey TO fk_sec_role_grantable_permission_permission_id;

ALTER TABLE spectra_security.sec_role_assignment RENAME CONSTRAINT role_assignment_pkey TO pk_sec_role_assignment;
ALTER TABLE spectra_security.sec_role_assignment RENAME CONSTRAINT role_assignment_user_id_fkey TO fk_sec_role_assignment_user_id;
ALTER TABLE spectra_security.sec_role_assignment RENAME CONSTRAINT role_assignment_role_id_fkey TO fk_sec_role_assignment_role_id;
ALTER TABLE spectra_security.sec_role_assignment RENAME CONSTRAINT ck_security_role_assignment_state TO ck_sec_role_assignment_state;
ALTER TABLE spectra_security.sec_role_assignment RENAME CONSTRAINT ck_security_role_assignment_period TO ck_sec_role_assignment_period;

ALTER TABLE spectra_security.sec_authorization_scope RENAME CONSTRAINT authorization_scope_pkey TO pk_sec_authorization_scope;
ALTER TABLE spectra_security.sec_authorization_scope RENAME CONSTRAINT ck_security_scope_mode TO ck_sec_authorization_scope_mode;
ALTER TABLE spectra_security.sec_authorization_scope RENAME CONSTRAINT ck_security_scope_resource TO ck_sec_authorization_scope_resource;

ALTER TABLE spectra_security.sec_assignment_permission_boundary RENAME CONSTRAINT assignment_permission_boundary_pkey TO pk_sec_assignment_permission_boundary;
ALTER TABLE spectra_security.sec_assignment_permission_boundary RENAME CONSTRAINT assignment_permission_boundary_assignment_id_fkey TO fk_sec_assignment_permission_boundary_assignment_id;
ALTER TABLE spectra_security.sec_assignment_permission_boundary RENAME CONSTRAINT assignment_permission_boundary_permission_id_fkey TO fk_sec_assignment_permission_boundary_permission_id;
ALTER TABLE spectra_security.sec_assignment_permission_boundary RENAME CONSTRAINT assignment_permission_boundary_scope_id_fkey TO fk_sec_assignment_permission_boundary_scope_id;

ALTER TABLE spectra_security.sec_assignment_grant_boundary RENAME CONSTRAINT assignment_grant_boundary_pkey TO pk_sec_assignment_grant_boundary;
ALTER TABLE spectra_security.sec_assignment_grant_boundary RENAME CONSTRAINT assignment_grant_boundary_assignment_id_fkey TO fk_sec_assignment_grant_boundary_assignment_id;
ALTER TABLE spectra_security.sec_assignment_grant_boundary RENAME CONSTRAINT assignment_grant_boundary_permission_id_fkey TO fk_sec_assignment_grant_boundary_permission_id;
ALTER TABLE spectra_security.sec_assignment_grant_boundary RENAME CONSTRAINT assignment_grant_boundary_scope_id_fkey TO fk_sec_assignment_grant_boundary_scope_id;

ALTER TABLE spectra_security.sec_scope_rule RENAME CONSTRAINT scope_rule_pkey TO pk_sec_scope_rule;
ALTER TABLE spectra_security.sec_scope_rule RENAME CONSTRAINT scope_rule_scope_id_fkey TO fk_sec_scope_rule_scope_id;
ALTER TABLE spectra_security.sec_scope_rule RENAME CONSTRAINT scope_rule_department_id_fkey TO fk_sec_scope_rule_department_id;
ALTER TABLE spectra_security.sec_scope_rule RENAME CONSTRAINT ck_security_scope_rule_type TO ck_sec_scope_rule_type;
ALTER TABLE spectra_security.sec_scope_rule RENAME CONSTRAINT ck_security_scope_rule_department TO ck_sec_scope_rule_department;

ALTER TABLE spectra_security.sec_authentication_identity RENAME CONSTRAINT authentication_identity_pkey TO pk_sec_authentication_identity;
ALTER TABLE spectra_security.sec_authentication_identity RENAME CONSTRAINT authentication_identity_user_id_fkey TO fk_sec_authentication_identity_user_id;
ALTER TABLE spectra_security.sec_authentication_identity RENAME CONSTRAINT ck_security_identity_state TO ck_sec_authentication_identity_state;
ALTER TABLE spectra_security.sec_authentication_identity RENAME CONSTRAINT uk_security_identity_identifier TO uk_sec_authentication_identity_identifier;

ALTER TABLE spectra_security.sec_password_credential RENAME CONSTRAINT password_credential_pkey TO pk_sec_password_credential;
ALTER TABLE spectra_security.sec_password_credential RENAME CONSTRAINT password_credential_user_id_fkey TO fk_sec_password_credential_user_id;

ALTER TABLE spectra_security.sec_security_client RENAME CONSTRAINT security_client_pkey TO pk_sec_security_client;
ALTER TABLE spectra_security.sec_security_client RENAME CONSTRAINT ck_security_client_state TO ck_sec_security_client_state;
ALTER TABLE spectra_security.sec_security_client RENAME CONSTRAINT uk_security_client_code TO uk_sec_security_client_code;

ALTER TABLE spectra_security.sec_authentication_method RENAME CONSTRAINT authentication_method_pkey TO pk_sec_authentication_method;
ALTER TABLE spectra_security.sec_authentication_method RENAME CONSTRAINT ck_security_auth_method_state TO ck_sec_authentication_method_state;
ALTER TABLE spectra_security.sec_authentication_method RENAME CONSTRAINT uk_security_auth_method_code TO uk_sec_authentication_method_code;

ALTER TABLE spectra_security.sec_client_auth_method RENAME CONSTRAINT client_auth_method_pkey TO pk_sec_client_auth_method;
ALTER TABLE spectra_security.sec_client_auth_method RENAME CONSTRAINT client_auth_method_client_id_fkey TO fk_sec_client_auth_method_client_id;
ALTER TABLE spectra_security.sec_client_auth_method RENAME CONSTRAINT client_auth_method_authentication_method_id_fkey TO fk_sec_client_auth_method_authentication_method_id;

ALTER TABLE spectra_security.sec_session_policy RENAME CONSTRAINT session_policy_pkey TO pk_sec_session_policy;
ALTER TABLE spectra_security.sec_session_policy RENAME CONSTRAINT session_policy_client_id_fkey TO fk_sec_session_policy_client_id;
ALTER TABLE spectra_security.sec_session_policy RENAME CONSTRAINT ck_security_session_mode TO ck_sec_session_policy_mode;
ALTER TABLE spectra_security.sec_session_policy RENAME CONSTRAINT ck_security_session_limits TO ck_sec_session_policy_limits;

ALTER TABLE spectra_security.sec_password_policy RENAME CONSTRAINT password_policy_pkey TO pk_sec_password_policy;
ALTER TABLE spectra_security.sec_password_policy RENAME CONSTRAINT ck_security_password_policy_key TO ck_sec_password_policy_key;
ALTER TABLE spectra_security.sec_password_policy RENAME CONSTRAINT ck_security_password_policy_length TO ck_sec_password_policy_length;

ALTER TABLE spectra_security.sec_mfa_enrollment RENAME CONSTRAINT mfa_enrollment_pkey TO pk_sec_mfa_enrollment;
ALTER TABLE spectra_security.sec_mfa_enrollment RENAME CONSTRAINT mfa_enrollment_user_id_fkey TO fk_sec_mfa_enrollment_user_id;
ALTER TABLE spectra_security.sec_mfa_enrollment RENAME CONSTRAINT ck_security_mfa_factor TO ck_sec_mfa_enrollment_factor;
ALTER TABLE spectra_security.sec_mfa_enrollment RENAME CONSTRAINT ck_security_mfa_state TO ck_sec_mfa_enrollment_state;

ALTER TABLE spectra_security.sec_totp_credential RENAME CONSTRAINT totp_credential_pkey TO pk_sec_totp_credential;
ALTER TABLE spectra_security.sec_totp_credential RENAME CONSTRAINT totp_credential_enrollment_id_fkey TO fk_sec_totp_credential_enrollment_id;

ALTER TABLE spectra_security.sec_recovery_code RENAME CONSTRAINT recovery_code_pkey TO pk_sec_recovery_code;
ALTER TABLE spectra_security.sec_recovery_code RENAME CONSTRAINT recovery_code_enrollment_id_fkey TO fk_sec_recovery_code_enrollment_id;
ALTER TABLE spectra_security.sec_recovery_code RENAME CONSTRAINT uk_security_recovery_code_hash TO uk_sec_recovery_code_hash;

ALTER TABLE spectra_security.sec_root_policy RENAME CONSTRAINT root_policy_pkey TO pk_sec_root_policy;
ALTER TABLE spectra_security.sec_root_policy RENAME CONSTRAINT ck_security_root_policy_key TO ck_sec_root_policy_key;
ALTER TABLE spectra_security.sec_root_policy RENAME CONSTRAINT ck_security_root_policy_limits TO ck_sec_root_policy_limits;

ALTER TABLE spectra_security.sec_security_audit_event RENAME CONSTRAINT security_audit_event_pkey TO pk_sec_security_audit_event;
ALTER TABLE spectra_security.sec_security_audit_event RENAME CONSTRAINT ck_security_audit_result TO ck_sec_security_audit_event_result;

ALTER TABLE spectra_security.sec_security_audit_retention_policy RENAME CONSTRAINT security_audit_retention_policy_pkey TO pk_sec_security_audit_retention_policy;
ALTER TABLE spectra_security.sec_security_audit_retention_policy RENAME CONSTRAINT ck_security_audit_hot_retention TO ck_sec_security_audit_retention_policy_hot_retention;
ALTER TABLE spectra_security.sec_security_audit_retention_policy RENAME CONSTRAINT ck_security_audit_total_retention TO ck_sec_security_audit_retention_policy_total_retention;
ALTER TABLE spectra_security.sec_security_audit_retention_policy RENAME CONSTRAINT ck_security_audit_retention_state TO ck_sec_security_audit_retention_policy_state;

ALTER TABLE spectra_security.sec_security_audit_archive_manifest RENAME CONSTRAINT security_audit_archive_manifest_pkey TO pk_sec_security_audit_archive_manifest;
ALTER TABLE spectra_security.sec_security_audit_archive_manifest RENAME CONSTRAINT security_audit_archive_manifest_partition_name_key TO uk_sec_security_audit_archive_manifest_partition_name;
ALTER TABLE spectra_security.sec_security_audit_archive_manifest RENAME CONSTRAINT ck_security_audit_archive_range TO ck_sec_security_audit_archive_manifest_range;
ALTER TABLE spectra_security.sec_security_audit_archive_manifest RENAME CONSTRAINT ck_security_audit_archive_state TO ck_sec_security_audit_archive_manifest_state;
ALTER TABLE spectra_security.sec_security_audit_archive_manifest RENAME CONSTRAINT ck_security_audit_archive_hash TO ck_sec_security_audit_archive_manifest_hash;

ALTER TABLE spectra_security.sec_security_change_outbox RENAME CONSTRAINT security_change_outbox_pkey TO pk_sec_security_change_outbox;

ALTER TABLE spectra_security.sec_role_menu RENAME CONSTRAINT role_menu_pkey TO pk_sec_role_menu;
ALTER TABLE spectra_security.sec_role_menu RENAME CONSTRAINT role_menu_role_id_fkey TO fk_sec_role_menu_role_id;
ALTER TABLE spectra_security.sec_role_menu RENAME CONSTRAINT role_menu_menu_id_fkey TO fk_sec_role_menu_menu_id;

-- Explicit indexes. IF EXISTS keeps this safe across PostgreSQL versions that
-- automatically rename an index together with its owning constraint.
ALTER INDEX IF EXISTS spectra_security.idx_security_role_assignment_user_state RENAME TO idx_sec_role_assignment_user_state;
ALTER INDEX IF EXISTS spectra_security.idx_security_role_assignment_role_state RENAME TO idx_sec_role_assignment_role_state;
ALTER INDEX IF EXISTS spectra_security.uk_security_scope_rule_department RENAME TO uk_sec_scope_rule_department;
ALTER INDEX IF EXISTS spectra_security.idx_security_scope_rule_department RENAME TO idx_sec_scope_rule_department;
ALTER INDEX IF EXISTS spectra_security.idx_security_identity_user_state RENAME TO idx_sec_authentication_identity_user_state;
ALTER INDEX IF EXISTS spectra_security.uk_security_mfa_user_factor_active RENAME TO uk_sec_mfa_enrollment_user_factor_active;
ALTER INDEX IF EXISTS spectra_security.idx_security_audit_event_time RENAME TO idx_sec_security_audit_event_occurred_at;
ALTER INDEX IF EXISTS spectra_security.idx_security_audit_event_type RENAME TO idx_sec_security_audit_event_type_occurred_at;
ALTER INDEX IF EXISTS spectra_security.idx_security_audit_event_operator RENAME TO idx_sec_security_audit_event_operator_occurred_at;
ALTER INDEX IF EXISTS spectra_security.idx_security_audit_event_target RENAME TO idx_sec_security_audit_event_target_occurred_at;
ALTER INDEX IF EXISTS spectra_security.idx_security_audit_archive_manifest_range RENAME TO idx_sec_security_audit_archive_manifest_range;
ALTER INDEX IF EXISTS spectra_security.idx_security_audit_archive_manifest_state RENAME TO idx_sec_security_audit_archive_manifest_state;
ALTER INDEX IF EXISTS spectra_security.idx_security_outbox_pending RENAME TO idx_sec_security_change_outbox_created_at;
ALTER INDEX IF EXISTS spectra_security.idx_security_role_menu_menu RENAME TO idx_sec_role_menu_menu_id;

-- Primary-key and unique-constraint indexes are also database objects and must
-- carry the same canonical names when PostgreSQL kept the old index name.
ALTER INDEX IF EXISTS spectra_security.permission_pkey RENAME TO pk_sec_permission;
ALTER INDEX IF EXISTS spectra_security.role_pkey RENAME TO pk_sec_role;
ALTER INDEX IF EXISTS spectra_security.role_permission_pkey RENAME TO pk_sec_role_permission;
ALTER INDEX IF EXISTS spectra_security.role_grantable_permission_pkey RENAME TO pk_sec_role_grantable_permission;
ALTER INDEX IF EXISTS spectra_security.role_assignment_pkey RENAME TO pk_sec_role_assignment;
ALTER INDEX IF EXISTS spectra_security.authorization_scope_pkey RENAME TO pk_sec_authorization_scope;
ALTER INDEX IF EXISTS spectra_security.assignment_permission_boundary_pkey RENAME TO pk_sec_assignment_permission_boundary;
ALTER INDEX IF EXISTS spectra_security.assignment_grant_boundary_pkey RENAME TO pk_sec_assignment_grant_boundary;
ALTER INDEX IF EXISTS spectra_security.scope_rule_pkey RENAME TO pk_sec_scope_rule;
ALTER INDEX IF EXISTS spectra_security.authentication_identity_pkey RENAME TO pk_sec_authentication_identity;
ALTER INDEX IF EXISTS spectra_security.password_credential_pkey RENAME TO pk_sec_password_credential;
ALTER INDEX IF EXISTS spectra_security.security_client_pkey RENAME TO pk_sec_security_client;
ALTER INDEX IF EXISTS spectra_security.authentication_method_pkey RENAME TO pk_sec_authentication_method;
ALTER INDEX IF EXISTS spectra_security.client_auth_method_pkey RENAME TO pk_sec_client_auth_method;
ALTER INDEX IF EXISTS spectra_security.session_policy_pkey RENAME TO pk_sec_session_policy;
ALTER INDEX IF EXISTS spectra_security.password_policy_pkey RENAME TO pk_sec_password_policy;
ALTER INDEX IF EXISTS spectra_security.mfa_enrollment_pkey RENAME TO pk_sec_mfa_enrollment;
ALTER INDEX IF EXISTS spectra_security.totp_credential_pkey RENAME TO pk_sec_totp_credential;
ALTER INDEX IF EXISTS spectra_security.recovery_code_pkey RENAME TO pk_sec_recovery_code;
ALTER INDEX IF EXISTS spectra_security.root_policy_pkey RENAME TO pk_sec_root_policy;
ALTER INDEX IF EXISTS spectra_security.security_audit_event_pkey RENAME TO pk_sec_security_audit_event;
ALTER INDEX IF EXISTS spectra_security.security_audit_retention_policy_pkey RENAME TO pk_sec_security_audit_retention_policy;
ALTER INDEX IF EXISTS spectra_security.security_audit_archive_manifest_pkey RENAME TO pk_sec_security_audit_archive_manifest;
ALTER INDEX IF EXISTS spectra_security.security_audit_archive_manifest_partition_name_key RENAME TO uk_sec_security_audit_archive_manifest_partition_name;
ALTER INDEX IF EXISTS spectra_security.security_change_outbox_pkey RENAME TO pk_sec_security_change_outbox;
ALTER INDEX IF EXISTS spectra_security.role_menu_pkey RENAME TO pk_sec_role_menu;

ALTER FUNCTION spectra_security.reject_audit_mutation() RENAME TO sec_reject_audit_mutation;
ALTER TRIGGER trg_security_audit_event_immutable ON spectra_security.sec_security_audit_event
    RENAME TO trg_sec_security_audit_event_immutable;
