-- 补齐单体服务监控历史采样表的字段注释。
COMMENT ON TABLE spectra_core.sys_service_monitor_sample IS '单体服务监控历史采样表';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.id IS '主键ID';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.collected_at IS '监控采集时间';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.cpu_usage IS 'CPU 使用率（百分比）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.cpu_logical_cores IS 'CPU 逻辑核心数';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.system_memory_usage IS '系统内存使用率（百分比）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.system_memory_total_bytes IS '系统内存总量（字节）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.system_memory_used_bytes IS '系统已使用内存（字节）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.system_memory_available_bytes IS '系统可用内存（字节）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.jvm_heap_usage IS 'JVM 堆内存使用率（百分比）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.jvm_heap_used_bytes IS 'JVM 已使用堆内存（字节）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.jvm_heap_max_bytes IS 'JVM 堆内存上限（字节）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.jvm_non_heap_used_bytes IS 'JVM 已使用非堆内存（字节）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.live_thread_count IS '当前活动线程数';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.peak_thread_count IS '线程峰值数量';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.gc_count IS '垃圾回收次数';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.qps IS '最近采样周期的请求速率（QPS）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.error_rate IS '最近采样周期的 HTTP 5xx 错误率（百分比）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.p95_response_ms IS '最近采样周期的请求响应时间 P95（毫秒）';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.request_metrics_available IS '是否采集到 HTTP 请求指标';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.status IS '采样时的服务状态：HEALTHY-健康，WARNING-警告，DEGRADED-降级，DOWN-不可用';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.created_by IS '创建人';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.created_at IS '创建时间';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.updated_by IS '最后更新人';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.updated_at IS '最后更新时间';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.deleted IS '删除时间';
COMMENT ON COLUMN spectra_core.sys_service_monitor_sample.version IS '乐观锁版本';
