-- Permission catalog seed generated from docs/security/permission-catalog.yaml.
-- Permission ids are deterministic so migration mapping and later RoleAssignment
-- imports can resolve the same permission by code without a second identity table.
INSERT INTO spectra_security.permission (
    id,
    code,
    name,
    resource_code,
    action_code,
    allowed_scope_modes,
    state,
    system_managed
)
VALUES
        (md5('account:read')::uuid, 'account:read', '认证账号查看', 'account', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('account:update')::uuid, 'account:update', '认证账号维护', 'account', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('user:create')::uuid, 'user:create', '用户创建', 'user', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('user:read')::uuid, 'user:read', '用户查看', 'user', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('user:update')::uuid, 'user:update', '用户资料维护', 'user', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('user:disable')::uuid, 'user:disable', '用户锁定/禁用/离职', 'user', 'disable', 'RULES', 'ACTIVE', FALSE),
        (md5('user:reset-password')::uuid, 'user:reset-password', '管理员重置密码', 'user', 'reset-password', 'RULES', 'ACTIVE', FALSE),
        (md5('user:assign-role')::uuid, 'user:assign-role', '用户分配角色', 'user', 'assign-role', 'RULES', 'ACTIVE', FALSE),
        (md5('user:unlock')::uuid, 'user:unlock', '用户解锁/启用/重新入职', 'user', 'unlock', 'RULES', 'ACTIVE', FALSE),
        (md5('role:create')::uuid, 'role:create', '角色创建', 'role', 'create', 'NONE', 'ACTIVE', FALSE),
        (md5('role:read')::uuid, 'role:read', '角色查看', 'role', 'read', 'NONE', 'ACTIVE', FALSE),
        (md5('role:update')::uuid, 'role:update', '角色资料维护', 'role', 'update', 'NONE', 'ACTIVE', FALSE),
        (md5('role:disable')::uuid, 'role:disable', '角色停用', 'role', 'disable', 'NONE', 'ACTIVE', FALSE),
        (md5('role:assign')::uuid, 'role:assign', '角色分配', 'role', 'assign', 'RULES', 'ACTIVE', FALSE),
        (md5('role:grant')::uuid, 'role:grant', '角色授予能力配置', 'role', 'grant', 'NONE', 'ACTIVE', FALSE),
        (md5('role:authority-level:update')::uuid, 'role:authority-level:update', '角色管理等级调整', 'role:authority-level', 'update', 'NONE', 'ACTIVE', FALSE),
        (md5('permission:read')::uuid, 'permission:read', '权限目录查看', 'permission', 'read', 'NONE', 'ACTIVE', FALSE),
        (md5('menu:create')::uuid, 'menu:create', '菜单创建', 'menu', 'create', 'NONE', 'ACTIVE', FALSE),
        (md5('menu:read')::uuid, 'menu:read', '菜单查看', 'menu', 'read', 'NONE', 'ACTIVE', FALSE),
        (md5('menu:update')::uuid, 'menu:update', '菜单维护', 'menu', 'update', 'NONE', 'ACTIVE', FALSE),
        (md5('menu:disable')::uuid, 'menu:disable', '菜单停用', 'menu', 'disable', 'NONE', 'ACTIVE', FALSE),
        (md5('department:create')::uuid, 'department:create', '部门创建', 'department', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('department:read')::uuid, 'department:read', '部门查看', 'department', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('department:update')::uuid, 'department:update', '部门维护/移动', 'department', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('department:disable')::uuid, 'department:disable', '部门停用', 'department', 'disable', 'RULES', 'ACTIVE', FALSE),
        (md5('dictionary:create')::uuid, 'dictionary:create', '字典创建', 'dictionary', 'create', 'NONE', 'ACTIVE', FALSE),
        (md5('dictionary:read')::uuid, 'dictionary:read', '字典查看', 'dictionary', 'read', 'NONE', 'ACTIVE', FALSE),
        (md5('dictionary:update')::uuid, 'dictionary:update', '字典维护', 'dictionary', 'update', 'NONE', 'ACTIVE', FALSE),
        (md5('dictionary:disable')::uuid, 'dictionary:disable', '字典停用', 'dictionary', 'disable', 'NONE', 'ACTIVE', FALSE),
        (md5('region:read')::uuid, 'region:read', '行政区划查看', 'region', 'read', 'NONE', 'ACTIVE', FALSE),
        (md5('session:read')::uuid, 'session:read', '在线会话查看', 'session', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('session:revoke')::uuid, 'session:revoke', '会话强制下线', 'session', 'revoke', 'RULES', 'ACTIVE', FALSE),
        (md5('audit:read')::uuid, 'audit:read', '安全审计查看', 'audit', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('audit:export')::uuid, 'audit:export', '安全审计导出', 'audit', 'export', 'RULES', 'ACTIVE', FALSE),
        (md5('security:auth-method:update')::uuid, 'security:auth-method:update', '认证方式配置', 'security:auth-method', 'update', 'NONE', 'ACTIVE', TRUE),
        (md5('security:session-policy:update')::uuid, 'security:session-policy:update', 'Session 策略配置', 'security:session-policy', 'update', 'NONE', 'ACTIVE', TRUE),
        (md5('security:password-policy:update')::uuid, 'security:password-policy:update', '密码策略配置', 'security:password-policy', 'update', 'NONE', 'ACTIVE', TRUE),
        (md5('security:root:manage')::uuid, 'security:root:manage', 'DEV_OPS Root 治理', 'security:root', 'manage', 'NONE', 'ACTIVE', TRUE),
        (md5('file:create')::uuid, 'file:create', '文件上传', 'file', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('file:read')::uuid, 'file:read', '文件查看', 'file', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('notification:read')::uuid, 'notification:read', '通知查看', 'notification', 'read', 'SELF', 'ACTIVE', FALSE),
        (md5('notification:update')::uuid, 'notification:update', '通知标记已读', 'notification', 'update', 'SELF', 'ACTIVE', FALSE),
        (md5('notification:delete')::uuid, 'notification:delete', '通知删除', 'notification', 'delete', 'SELF', 'ACTIVE', FALSE),
        (md5('notification-setting:read')::uuid, 'notification-setting:read', '通知设置查看', 'notification-setting', 'read', 'SELF', 'ACTIVE', FALSE),
        (md5('notification-setting:update')::uuid, 'notification-setting:update', '通知设置维护', 'notification-setting', 'update', 'SELF', 'ACTIVE', FALSE),
        (md5('ai:create')::uuid, 'ai:create', 'AI 会话创建', 'ai', 'create', 'SELF', 'ACTIVE', FALSE),
        (md5('ai:read')::uuid, 'ai:read', 'AI 会话查看', 'ai', 'read', 'SELF', 'ACTIVE', FALSE),
        (md5('ai:update')::uuid, 'ai:update', 'AI 会话维护', 'ai', 'update', 'SELF', 'ACTIVE', FALSE),
        (md5('ai:delete')::uuid, 'ai:delete', 'AI 会话删除', 'ai', 'delete', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:application-type:create')::uuid, 'oa:application-type:create', 'OA 申请类型创建', 'oa:application-type', 'create', 'NONE', 'ACTIVE', FALSE),
        (md5('oa:application-type:read')::uuid, 'oa:application-type:read', 'OA 申请类型查看', 'oa:application-type', 'read', 'NONE', 'ACTIVE', FALSE),
        (md5('oa:application-type:update')::uuid, 'oa:application-type:update', 'OA 申请类型维护', 'oa:application-type', 'update', 'NONE', 'ACTIVE', FALSE),
        (md5('oa:application-type:disable')::uuid, 'oa:application-type:disable', 'OA 申请类型停用', 'oa:application-type', 'disable', 'NONE', 'ACTIVE', FALSE),
        (md5('oa:application:read')::uuid, 'oa:application:read', 'OA 申请查看', 'oa:application', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:application:update')::uuid, 'oa:application:update', 'OA 申请处理', 'oa:application', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:asset:create')::uuid, 'oa:asset:create', 'OA 资产创建', 'oa:asset', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:asset:read')::uuid, 'oa:asset:read', 'OA 资产查看', 'oa:asset', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:asset:update')::uuid, 'oa:asset:update', 'OA 资产维护', 'oa:asset', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:calendar:create')::uuid, 'oa:calendar:create', 'OA 日历创建', 'oa:calendar', 'create', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:calendar:read')::uuid, 'oa:calendar:read', 'OA 日历查看', 'oa:calendar', 'read', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:calendar:update')::uuid, 'oa:calendar:update', 'OA 日历维护', 'oa:calendar', 'update', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:calendar:delete')::uuid, 'oa:calendar:delete', 'OA 日历删除', 'oa:calendar', 'delete', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:contract:create')::uuid, 'oa:contract:create', 'OA 合同创建', 'oa:contract', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:contract:read')::uuid, 'oa:contract:read', 'OA 合同查看', 'oa:contract', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:contract:update')::uuid, 'oa:contract:update', 'OA 合同维护', 'oa:contract', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:contract:delete')::uuid, 'oa:contract:delete', 'OA 合同归档/删除', 'oa:contract', 'delete', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:contact:read')::uuid, 'oa:contact:read', 'OA 联系人查看', 'oa:contact', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:document:create')::uuid, 'oa:document:create', 'OA 文档创建', 'oa:document', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:document:read')::uuid, 'oa:document:read', 'OA 文档查看', 'oa:document', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:document:update')::uuid, 'oa:document:update', 'OA 文档维护', 'oa:document', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:leave:create')::uuid, 'oa:leave:create', 'OA 请假申请', 'oa:leave', 'create', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:leave:read')::uuid, 'oa:leave:read', 'OA 请假查看', 'oa:leave', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:leave:update')::uuid, 'oa:leave:update', 'OA 请假审批/处理', 'oa:leave', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:meeting:create')::uuid, 'oa:meeting:create', 'OA 会议创建', 'oa:meeting', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:meeting:read')::uuid, 'oa:meeting:read', 'OA 会议查看', 'oa:meeting', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:meeting:update')::uuid, 'oa:meeting:update', 'OA 会议维护', 'oa:meeting', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:notice:create')::uuid, 'oa:notice:create', 'OA 公告创建', 'oa:notice', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:notice:read')::uuid, 'oa:notice:read', 'OA 公告查看', 'oa:notice', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:notice:update')::uuid, 'oa:notice:update', 'OA 公告维护', 'oa:notice', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:purchase:create')::uuid, 'oa:purchase:create', 'OA 采购创建', 'oa:purchase', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:purchase:read')::uuid, 'oa:purchase:read', 'OA 采购查看', 'oa:purchase', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:purchase:update')::uuid, 'oa:purchase:update', 'OA 采购维护', 'oa:purchase', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:purchase:execute')::uuid, 'oa:purchase:execute', 'OA 采购执行', 'oa:purchase', 'execute', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:purchase:receive')::uuid, 'oa:purchase:receive', 'OA 采购收货', 'oa:purchase', 'receive', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:reimbursement:create')::uuid, 'oa:reimbursement:create', 'OA 报销创建', 'oa:reimbursement', 'create', 'SELF', 'ACTIVE', FALSE),
        (md5('oa:reimbursement:read')::uuid, 'oa:reimbursement:read', 'OA 报销查看', 'oa:reimbursement', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:reimbursement:update')::uuid, 'oa:reimbursement:update', 'OA 报销维护', 'oa:reimbursement', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:reimbursement:pay')::uuid, 'oa:reimbursement:pay', 'OA 报销付款', 'oa:reimbursement', 'pay', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:report:read')::uuid, 'oa:report:read', 'OA 报表查看', 'oa:report', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('oa:workbench:read')::uuid, 'oa:workbench:read', 'OA 工作台查看', 'oa:workbench', 'read', 'SELF', 'ACTIVE', FALSE),
        (md5('workflow:form:create')::uuid, 'workflow:form:create', '流程表单创建', 'workflow:form', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:form:read')::uuid, 'workflow:form:read', '流程表单查看', 'workflow:form', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:form:update')::uuid, 'workflow:form:update', '流程表单维护', 'workflow:form', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:form:disable')::uuid, 'workflow:form:disable', '流程表单停用', 'workflow:form', 'disable', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:process:create')::uuid, 'workflow:process:create', '流程定义创建', 'workflow:process', 'create', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:process:read')::uuid, 'workflow:process:read', '流程定义查看', 'workflow:process', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:process:update')::uuid, 'workflow:process:update', '流程定义维护', 'workflow:process', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:instance:create')::uuid, 'workflow:instance:create', '流程实例发起', 'workflow:instance', 'create', 'SELF', 'ACTIVE', FALSE),
        (md5('workflow:instance:read')::uuid, 'workflow:instance:read', '流程实例查看', 'workflow:instance', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:instance:update')::uuid, 'workflow:instance:update', '流程实例处理', 'workflow:instance', 'update', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:task:read')::uuid, 'workflow:task:read', '流程任务查看', 'workflow:task', 'read', 'RULES', 'ACTIVE', FALSE),
        (md5('workflow:task:update')::uuid, 'workflow:task:update', '流程任务处理', 'workflow:task', 'update', 'RULES', 'ACTIVE', FALSE)
ON CONFLICT (code) DO NOTHING;
