CREATE TABLE SPECTRA.SYS_LICENSE_MANAGER
(
    ID         NUMBER(19)   NOT NULL,

    ISSUED_AT  TIMESTAMP(6) NOT NULL,
    EXPIRY_AT  TIMESTAMP(6) NOT NULL,

    PASSWORD   VARCHAR2(255),
    CERT_PUB   BLOB,
    CERT_PRI   BLOB,

    ENABLE     NUMBER(1),
    CREATED_BY NUMBER(19),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_BY NUMBER(19),
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    DELETED    TIMESTAMP(6),
    VERSION    NUMBER(19) DEFAULT 0
);

CREATE UNIQUE INDEX IDX_PK_SYS_LICENSE_MANAGER_ID ON SPECTRA.SYS_LICENSE_MANAGER (ID);
ALTER TABLE SPECTRA.SYS_LICENSE_MANAGER
    ADD CONSTRAINT PK_SYS_LICENSE_MANAGER_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_LICENSE_MANAGER_ID;

COMMENT ON TABLE SPECTRA.SYS_LICENSE_MANAGER IS '系统配置表';

COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.ID IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.CREATED_BY IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.UPDATED_AT IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.DELETED IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_LICENSE_MANAGER.VERSION IS '乐观锁版本号,默认0';
