CREATE UNIQUE INDEX IDX_PK_SYS_AUTHORITY_ID ON SYS_AUTHORITY(ID);
ALTER TABLE SYS_AUTHORITY
    ADD CONSTRAINT PK_SYS_AUTHORITY_ID PRIMARY KEY (ID)
USING INDEX IDX_PK_SYS_AUTHORITY_ID;
CREATE UNIQUE INDEX IDX_UK_SYS_AUTHORITY_CODE ON SYS_AUTHORITY(CODE);

CREATE UNIQUE INDEX IDX_PK_SYS_CONFIG_ID ON SYS_CONFIG(ID);
ALTER TABLE SYS_CONFIG
    ADD CONSTRAINT PK_SYS_CONFIG_ID PRIMARY KEY (ID)
USING INDEX IDX_PK_SYS_CONFIG_ID;
CREATE UNIQUE INDEX IDX_UK_SYS_CONFIG_KEY ON SYS_CONFIG(KEY);

CREATE UNIQUE INDEX IDX_PK_SYS_DICT_DATA_ID ON SYS_DICT_DATA(ID);
ALTER TABLE SYS_DICT_DATA
    ADD CONSTRAINT PK_SYS_DICT_DATA_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_DICT_DATA_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_DICT_GROUP_ID ON SYS_DICT_GROUP(ID);
ALTER TABLE SYS_DICT_GROUP
    ADD CONSTRAINT PK_SYS_DICT_GROUP_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_DICT_GROUP_ID;
CREATE UNIQUE INDEX IDX_UK_SYS_DICT_GROUP_CODE ON SYS_DICT_GROUP(CODE);

CREATE UNIQUE INDEX IDX_PK_SYS_MENU_ID ON SYS_MENU(ID);
ALTER TABLE SYS_MENU
    ADD CONSTRAINT PK_SYS_MENU_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_MENU_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_OPERATION_LOG_ID ON SYS_OPERATION_LOG(ID);
ALTER TABLE SYS_OPERATION_LOG
    ADD CONSTRAINT PK_SYS_OPERATION_LOG_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_OPERATION_LOG_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_ORGANIZATION_ID ON SYS_ORGANIZATION(ID);
ALTER TABLE SYS_ORGANIZATION
    ADD CONSTRAINT PK_SYS_ORGANIZATION_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_ORGANIZATION_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_REL_ROLE_AUTHORITY_ID ON SYS_REL_ROLE_AUTHORITY(ID);
ALTER TABLE SYS_REL_ROLE_AUTHORITY
    ADD CONSTRAINT PK_SYS_REL_ROLE_AUTHORITY_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_REL_ROLE_AUTHORITY_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_REL_ROLE_MENU_ID ON SYS_REL_ROLE_MENU(ID);
ALTER TABLE SYS_REL_ROLE_MENU
    ADD CONSTRAINT PK_SYS_REL_ROLE_MENU_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_REL_ROLE_MENU_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_REL_USER_ROLE_ID ON SYS_REL_USER_ROLE(ID);
ALTER TABLE SYS_REL_USER_ROLE
    ADD CONSTRAINT PK_SYS_REL_USER_ROLE_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_REL_USER_ROLE_ID;

CREATE UNIQUE INDEX IDX_PK_SYS_ROLE_ID ON SYS_ROLE(ID);
ALTER TABLE SYS_ROLE
    ADD CONSTRAINT PK_SYS_ROLE_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_ROLE_ID;
CREATE UNIQUE INDEX IDX_UK_SYS_ROLE_CODE ON SYS_ROLE(CODE);

CREATE UNIQUE INDEX IDX_PK_SYS_USER_ID ON SYS_USER(ID);
ALTER TABLE SYS_USER
    ADD CONSTRAINT PK_SYS_USER_ID PRIMARY KEY (ID)
        USING INDEX IDX_PK_SYS_USER_ID;
CREATE UNIQUE INDEX IDX_UK_SYS_USER_NAME ON SYS_USER(NAME);
CREATE UNIQUE INDEX IDX_UK_SYS_USER_EMAIL ON SYS_USER(EMAIL);