CREATE TABLE SPECTRA.SYS_CONFIG
(
    ID         NUMBER(19)    NOT NULL,

    KEY        VARCHAR2(100) NOT NULL,
    VALUE      VARCHAR2(100) NOT NULL,
    REMARKS    VARCHAR2(255),

    CREATED_BY NUMBER(19),
    CREATED_AT TIMESTAMP(6)  NOT NULL,
    UPDATED_BY NUMBER(19),
    UPDATED_AT TIMESTAMP(6)  NOT NULL,
    DELETED    TIMESTAMP(6),
    VERSION    NUMBER(19) DEFAULT 0
);
COMMENT ON TABLE SPECTRA.SYS_CONFIG IS '系统配置表';

COMMENT ON COLUMN SPECTRA.SYS_CONFIG.ID IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.CREATED_BY IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.CREATED_AT IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.UPDATED_AT IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.DELETED IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.VERSION IS '乐观锁版本号,默认0';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.KEY IS '配置key';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.VALUE IS '配置VALUE';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG.REMARKS IS '备注说明';