// @no-log
### 用户登录
# @name 用户登录
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "yangxj96@gmail.com",
  "password": "sysadmin",
  "code": "1234"
}

> {%
    client.global.set("token", response.body.data.access_token);
%}

### 用户登出
# @name 用户登出
POST {{host}}/auth/logout
Authorization: Bearer {{token}}