-- 订单中心业务
-- 订单主表
CREATE TABLE "SPECTRA"."OMS_ORDER"
(
    "ID"           NUMBER(19, 0)            NOT NULL,

    "USER_ID"      NUMBER(19, 0)            NOT NULL,
    "ORDER_NO"     NUMBER(19, 0)            NOT NULL,
    "ORDER_STATUS" NUMBER(5)                NOT NULL,
    "ORDER_TYPE"   NUMBER(5)                NOT NULL,

    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"      TIMESTAMP WITH TIME ZONE,
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.OMS_ORDER IS '订单主表';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."USER_ID" IS '用户ID';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."ORDER_NO" IS '订单编号';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."ORDER_STATUS" IS '订单状态';
COMMENT ON COLUMN SPECTRA.OMS_ORDER."ORDER_TYPE" IS '订单类型';

CREATE UNIQUE INDEX "IDX_UK_OMS_ORDER_ID" ON "SPECTRA"."OMS_ORDER" (ID);
ALTER TABLE "SPECTRA"."OMS_ORDER"
    ADD CONSTRAINT "PK_OMS_ORDER_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_OMS_ORDER_ID";