-- 用户表
CREATE TABLE "SPECTRA"."SYS_USER"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    -- 核心身份
    "USERNAME"   VARCHAR2(100)            NOT NULL,
    "AVATAR"     VARCHAR2(255),
    "STATUS"     NUMBER(1, 0)  DEFAULT 1  NOT NULL,
    -- 扩展信息
    "REAL_NAME"  VARCHAR2(50),
    "GENDER"     NUMBER(1, 0)  DEFAULT 0,
    "BIRTHDAY"   DATE,
    "PHONE"      VARCHAR2(20),
    "EMAIL"      VARCHAR2(100),
    "COUNTRY"    VARCHAR2(50),
    "CITY"       VARCHAR2(50),
    "LANGUAGE"   VARCHAR2(10)  DEFAULT 'zh-CN',
    "TIMEZONE"   VARCHAR2(40)  DEFAULT 'Asia/Shanghai',

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_USER IS '用户表';
COMMENT ON COLUMN SPECTRA.SYS_USER."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_USER."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_USER."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_USER."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_USER."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_USER."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_USER."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.SYS_USER."USERNAME" IS '显示名称';
COMMENT ON COLUMN SPECTRA.SYS_USER."AVATAR" IS '头像';
COMMENT ON COLUMN SPECTRA.SYS_USER."STATUS" IS '状态 (1:正常 0:禁用)';
COMMENT ON COLUMN SPECTRA.SYS_USER."REAL_NAME" IS '真实姓名';
COMMENT ON COLUMN SPECTRA.SYS_USER."GENDER" IS '性别(0:保密)';
COMMENT ON COLUMN SPECTRA.SYS_USER."BIRTHDAY" IS '生日';
COMMENT ON COLUMN SPECTRA.SYS_USER."PHONE" IS '手机号';
COMMENT ON COLUMN SPECTRA.SYS_USER."EMAIL" IS '邮箱';
COMMENT ON COLUMN SPECTRA.SYS_USER."COUNTRY" IS '国家';
COMMENT ON COLUMN SPECTRA.SYS_USER."CITY" IS '城市';
COMMENT ON COLUMN SPECTRA.SYS_USER."LANGUAGE" IS '语言';
COMMENT ON COLUMN SPECTRA.SYS_USER."TIMEZONE" IS '时区';

CREATE UNIQUE INDEX "IDX_UK_SYS_USER_ID" ON "SPECTRA"."SYS_USER" (ID);
ALTER TABLE "SPECTRA"."SYS_USER"
    ADD CONSTRAINT "PK_SYS_USER_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_USER_ID";

-- 账号表
CREATE TABLE "SPECTRA"."SYS_ACCOUNT"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "USER_ID"    NUMBER(19, 0)            NOT NULL,
    "TYPE"       NUMBER(10, 0)            NOT NULL,

    "LOGIN_NAME" VARCHAR2(100),
    "PASSWORD"   VARCHAR2(255),
    "PHONE"      VARCHAR2(20),
    "EMAIL"      VARCHAR2(100),
    "OPENID"     VARCHAR2(100),
    "UNIONID"    VARCHAR2(100),
    "PROVIDER"   VARCHAR2(50),
    "STATUS"     NUMBER(1, 0)  DEFAULT 1  NOT NULL,
    "VERIFIED"   NUMBER(1, 0)  DEFAULT 0  NOT NULL,
    "EXPIRES_AT" TIMESTAMP WITH TIME ZONE,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0,

    CONSTRAINT chk_account_identifier CHECK
        (
        (TYPE = 1 AND LOGIN_NAME IS NOT NULL) OR
        (TYPE = 2 AND PHONE IS NOT NULL) OR
        (TYPE = 3 AND EMAIL IS NOT NULL) OR
        (TYPE = 4 AND OPENID IS NOT NULL)
        )
);
COMMENT ON TABLE SPECTRA.SYS_ACCOUNT IS '表说明';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."USER_ID" IS '用户ID';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."TYPE" IS '登录类型';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."LOGIN_NAME" IS '用户名（用于账号密码登录）';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."PASSWORD" IS '密码(仅用作账号密码登录)';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."PHONE" IS '手机号（用于短信登录）';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."EMAIL" IS '邮箱（用于邮箱验证码登录）';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."OPENID" IS '微信 openid';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."UNIONID" IS '微信 unionid（跨应用唯一）';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."PROVIDER" IS '第三方来源：WECHAT, ALIPAY, APPLE 等';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."STATUS" IS '1:正常 2:禁用 3:未验证';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."VERIFIED" IS '0:未验证 1:已验证（如手机号/邮箱）';
COMMENT ON COLUMN SPECTRA.SYS_ACCOUNT."EXPIRES_AT" IS '用于临时账号（如扫码未确认）';

CREATE UNIQUE INDEX "IDX_UK_SYS_ACCOUNT_ID" ON "SPECTRA"."SYS_ACCOUNT" (ID);
ALTER TABLE "SPECTRA"."SYS_ACCOUNT"
    ADD CONSTRAINT "PK_SYS_ACCOUNT_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_ACCOUNT_ID";
-- 用户名 索引
CREATE UNIQUE INDEX "UK_SYS_ACCOUNT_LOGIN_NAME" ON "SPECTRA"."SYS_ACCOUNT" (CASE WHEN DELETED IS NULL AND LOGIN_NAME IS NULL THEN LOGIN_NAME END);
-- 手机号 索引
CREATE UNIQUE INDEX "UK_SYS_ACCOUNT_PHONE" ON "SPECTRA"."SYS_ACCOUNT" (CASE WHEN DELETED IS NULL AND PHONE IS NULL THEN PHONE END);
-- OPENID 索引
CREATE UNIQUE INDEX "UK_SYS_ACCOUNT_OPENID" ON "SPECTRA"."SYS_ACCOUNT" (CASE WHEN DELETED IS NULL AND OPENID IS NULL THEN OPENID END);

-- 角色表
CREATE TABLE "SPECTRA"."SYS_ROLE"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "NAME"       VARCHAR2(100),
    "CODE"       VARCHAR2(100),
    "STATE"      NUMBER(1, 0)  DEFAULT 1,
    "SCOPE"      INT,
    "BUILTIN"    NUMBER(1, 0)  DEFAULT 1,
    "REMARK"     CLOB,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_ROLE IS '角色表';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."NAME" IS '名称';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."CODE" IS '编码';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."STATE" IS '状态';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."SCOPE" IS '范围';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."BUILTIN" IS '是否内置';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_ROLE_ID" ON "SPECTRA"."SYS_ROLE" (ID);
ALTER TABLE "SPECTRA"."SYS_ROLE"
    ADD CONSTRAINT "PK_SYS_ROLE_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_ROLE_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_ROLE_CODE" ON "SPECTRA"."SYS_ROLE" ("CODE");

-- 权限表
CREATE TABLE "SPECTRA"."SYS_AUTHORITY"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "PID"        NUMBER(19, 0),
    "NAME"       VARCHAR2(100)            NOT NULL,
    "CODE"       VARCHAR2(100)            NOT NULL,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_AUTHORITY IS '权限表';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."PID" IS '父级ID,用于构建树形结构';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."NAME" IS '权限名称';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."CODE" IS '权限编码';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_AUTHORITY_ID" ON "SPECTRA"."SYS_AUTHORITY" (ID);
ALTER TABLE "SPECTRA"."SYS_AUTHORITY"
    ADD CONSTRAINT "PK_SYS_AUTHORITY_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_AUTHORITY_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_AUTHORITY_CODE" ON "SPECTRA"."SYS_AUTHORITY" ("CODE");

-- 关联表:角色-权限
CREATE TABLE "SPECTRA"."SYS_REL_ROLE_AUTHORITY"
(
    "ID"           NUMBER(19, 0)            NOT NULL,

    "ROLE_ID"      NUMBER(19, 0)            NOT NULL,
    "AUTHORITY_ID" NUMBER(19, 0)            NOT NULL,

    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"      TIMESTAMP WITH TIME ZONE,
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_REL_ROLE_AUTHORITY IS '角色表<->权限表';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."AUTHORITY_ID" IS '权限ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_REL_ROLE_AUTHORITY_ID" ON "SPECTRA"."SYS_REL_ROLE_AUTHORITY" (ID);
ALTER TABLE "SPECTRA"."SYS_REL_ROLE_AUTHORITY"
    ADD CONSTRAINT "PK_SYS_REL_ROLE_AUTHORITY_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_REL_ROLE_AUTHORITY_ID";

-- 关联表:角色-菜单
CREATE TABLE "SPECTRA"."SYS_REL_ROLE_MENU"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "ROLE_ID"    NUMBER(19, 0)            NOT NULL,
    "MENU_ID"    NUMBER(19, 0)            NOT NULL,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_REL_ROLE_MENU IS '角色表<->菜单表';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."DELETED" IS '软删除标识';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_REL_ROLE_MENU_ID" ON "SPECTRA"."SYS_REL_ROLE_MENU" (ID);
ALTER TABLE "SPECTRA"."SYS_REL_ROLE_MENU"
    ADD CONSTRAINT "PK_SYS_REL_ROLE_MENU_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_REL_ROLE_MENU_ID";

-- 关联表:用户-角色
CREATE TABLE "SPECTRA"."SYS_REL_USER_ROLE"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "USER_ID"    NUMBER(19, 0)            NOT NULL,
    "ROLE_ID"    NUMBER(19, 0)            NOT NULL,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_REL_USER_ROLE IS '用户表<->角色表';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."USER_ID" IS '用户ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_REL_USER_ROLE_ID" ON "SPECTRA"."SYS_REL_USER_ROLE" (ID);
ALTER TABLE "SPECTRA"."SYS_REL_USER_ROLE"
    ADD CONSTRAINT "PK_SYS_REL_USER_ROLE_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_REL_USER_ROLE_ID";


