-- 文件上传信息
CREATE TABLE "SPECTRA"."SYS_FILE_INFO"
(
    "ID"           NUMBER(19, 0)            NOT NULL,

    "FILE_NAME"    VARCHAR2(32)             NOT NULL,
    "ORIGIN_NAME"  VARCHAR2(50)             NOT NULL,
    "SUFFIX"       VARCHAR2(50)             NOT NULL,
    "PATH"         VARCHAR2(500)            NOT NULL,
    "SIZE"         NUMBER(19, 0)            NOT NULL,
    "HASH"         VARCHAR2(64),
    "STORAGE_TYPE" NUMBER(5, 0)             NOT NULL,

    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"      TIMESTAMP WITH TIME ZONE,
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_FILE_INFO IS '文件上传信息';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."FILE_NAME" IS '生成的32位的文件名称';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."ORIGIN_NAME" IS '文件源名称';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."SUFFIX" IS '文件后缀';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."PATH" IS '文件存储位置';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."SIZE" IS '文件大小';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."HASH" IS '文件hash值';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."STORAGE_TYPE" IS '文件存储类型,';

CREATE UNIQUE INDEX "IDX_SYS_FILE_INFO_ID" ON "SPECTRA"."SYS_FILE_INFO" (ID);
ALTER TABLE "SPECTRA"."SYS_FILE_INFO"
    ADD CONSTRAINT "PK_SYS_FILE_INFO" PRIMARY KEY (ID) USING INDEX "IDX_SYS_FILE_INFO_ID";

-- 文件分片上传信息处理
CREATE TABLE "SPECTRA"."SYS_FILE_CHUNK"
(
    "ID"           NUMBER(19, 0)            NOT NULL,

    "FILE_NAME"    VARCHAR2(255)            NOT NULL,
    "FILE_ID"      VARCHAR2(64)             NOT NULL,
    "CHUNK_INDEX"  NUMBER(10, 0)            NOT NULL,
    "TOTAL_CHUNKS" NUMBER(10, 0)            NOT NULL,
    "CHUNK_PATH"   VARCHAR2(500)            NOT NULL,
    "CHUNK_SIZE"   NUMBER(19, 0)            NOT NULL,

    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"      TIMESTAMP WITH TIME ZONE,
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_FILE_CHUNK IS '文件上传信息';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."FILE_NAME" IS '文件原名';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."FILE_ID" IS '文件唯一标识（如 SHA256 或 UUID）';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CHUNK_INDEX" IS '分片序号（从 0 开始）';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."TOTAL_CHUNKS" IS '总分片数（冗余，便于校验）';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CHUNK_PATH" IS '分片在磁盘/OSS 的存储路径或 Key';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CHUNK_SIZE" IS '当前分片字节数';

CREATE UNIQUE INDEX "IDX_SYS_FILE_CHUNK_ID" ON "SPECTRA"."SYS_FILE_CHUNK" (ID);
ALTER TABLE "SPECTRA"."SYS_FILE_CHUNK"
    ADD CONSTRAINT "PK_SYS_FILE_CHUNK" PRIMARY KEY (ID) USING INDEX "IDX_SYS_FILE_CHUNK_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_SYS_FILE_CHUNK_FILE_ID" ON "SPECTRA"."SYS_FILE_CHUNK" ("FILE_ID");
