-- 系统配置表
CREATE TABLE "SPECTRA"."SYS_CONFIG"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "KEY"        VARCHAR2(100)            NOT NULL,
    "VALUE"      VARCHAR2(100)            NOT NULL,
    "REMARKS"    VARCHAR2(255),

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_CONFIG IS '系统配置表';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."VERSION" IS '乐观锁版本号,默认0';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."KEY" IS '配置key';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."VALUE" IS '配置VALUE';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."REMARKS" IS '备注说明';

CREATE UNIQUE INDEX "IDX_UK_SYS_CONFIG_ID" ON "SPECTRA"."SYS_CONFIG" (ID);
ALTER TABLE "SPECTRA"."SYS_CONFIG"
    ADD CONSTRAINT "PK_SYS_CONFIG_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_CONFIG_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_CONFIG_KEY" ON "SPECTRA"."SYS_CONFIG" ("KEY");

-- 菜单表
CREATE TABLE "SPECTRA"."SYS_MENU"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "NAME"       VARCHAR2(100)            NOT NULL,
    "PID"        NUMBER(19, 0),
    "ICON"       VARCHAR2(100),
    "PATH"       VARCHAR2(255)            NOT NULL,
    "COMPONENT"  VARCHAR2(100)            NOT NULL,
    "LAYOUT"     VARCHAR2(100),
    "SORT"       INTEGER       DEFAULT 0,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_MENU IS '菜单表';
COMMENT ON COLUMN SPECTRA.SYS_MENU."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_MENU."NAME" IS '名称';
COMMENT ON COLUMN SPECTRA.SYS_MENU."PID" IS '父级ID';
COMMENT ON COLUMN SPECTRA.SYS_MENU."ICON" IS '图标';
COMMENT ON COLUMN SPECTRA.SYS_MENU."PATH" IS '请求路径';
COMMENT ON COLUMN SPECTRA.SYS_MENU."COMPONENT" IS '组件路径,为空则使用布局组件';
COMMENT ON COLUMN SPECTRA.SYS_MENU."LAYOUT" IS '布局';
COMMENT ON COLUMN SPECTRA.SYS_MENU."SORT" IS '排序';
COMMENT ON COLUMN SPECTRA.SYS_MENU."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_MENU."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_MENU."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_MENU."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_MENU."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_MENU."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_MENU_ID" ON "SPECTRA"."SYS_MENU" (ID);
ALTER TABLE "SPECTRA"."SYS_MENU"
    ADD CONSTRAINT "PK_SYS_MENU_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_MENU_ID";

-- 操作日志表
CREATE TABLE "SPECTRA"."SYS_LOG"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "TYPE"       NUMBER(10),
    "EXPLAIN"    VARCHAR2(255),
    "STATUS"     SMALLINT,
    "IP"         VARCHAR2(15),
    "METHOD"     VARCHAR2(255),
    "URL"        VARCHAR2(255),
    "ARGS"       BLOB,
    "RESULT"     BLOB,
    "TIME_COST"  NUMBER(19, 0),

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_LOG IS '操作日志表';
COMMENT ON COLUMN SPECTRA.SYS_LOG."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_LOG."TYPE" IS '日志类型';
COMMENT ON COLUMN SPECTRA.SYS_LOG."EXPLAIN" IS '日志说明';
COMMENT ON COLUMN SPECTRA.SYS_LOG."STATUS" IS '请求状态';
COMMENT ON COLUMN SPECTRA.SYS_LOG."IP" IS '来源IP';
COMMENT ON COLUMN SPECTRA.SYS_LOG."METHOD" IS '请求方法';
COMMENT ON COLUMN SPECTRA.SYS_LOG."URL" IS '请求URL';
COMMENT ON COLUMN SPECTRA.SYS_LOG."ARGS" IS '请求参数';
COMMENT ON COLUMN SPECTRA.SYS_LOG."RESULT" IS '请求响应';
COMMENT ON COLUMN SPECTRA.SYS_LOG."TIME_COST" IS '耗时';
COMMENT ON COLUMN SPECTRA.SYS_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_LOG."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_LOG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_LOG."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_LOG."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_LOG."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_LOG_ID" ON "SPECTRA"."SYS_LOG" (ID);
ALTER TABLE "SPECTRA"."SYS_LOG"
    ADD CONSTRAINT "PK_SYS_LOG_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_LOG_ID";

-- 组织机构表
CREATE TABLE "SPECTRA"."SYS_ORGANIZATION"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "PID"        NUMBER(19, 0),
    "NAME"       VARCHAR2(100)            NOT NULL,
    "CODE"       VARCHAR2(100)            NOT NULL,
    "TYPE"       SMALLINT,
    "PATH"       VARCHAR2(255),
    "REMARK"     VARCHAR2(255),

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_ORGANIZATION IS '组织机构表';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."PID" IS '上级ID';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."NAME" IS '名称';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."CODE" IS '编码';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."TYPE" IS '公司类型';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."PATH" IS '组织机构路径';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_ORGANIZATION_ID" ON "SPECTRA"."SYS_ORGANIZATION" (ID);
ALTER TABLE "SPECTRA"."SYS_ORGANIZATION"
    ADD CONSTRAINT "PK_SYS_ORGANIZATION_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_ORGANIZATION_ID";
