-- 字典数据表
CREATE TABLE "SPECTRA"."SYS_DICT_DATA"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "GID"        NUMBER(19, 0)            NOT NULL,
    "LABEL"      VARCHAR2(100)            NOT NULL,
    "VALUE"      VARCHAR2(100)            NOT NULL,
    "SORT"       SMALLINT      DEFAULT 0  NOT NULL,
    "STATE"      SMALLINT                 NOT NULL,
    "REMARK"     VARCHAR2(255),

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_DICT_DATA IS '字典数据表';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."GID" IS '字典组ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."LABEL" IS '标签';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."VALUE" IS '值';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."SORT" IS '排序';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."STATE" IS '状态';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_DICT_DATA_ID" ON "SPECTRA"."SYS_DICT_DATA" (ID);
ALTER TABLE "SPECTRA"."SYS_DICT_DATA"
    ADD CONSTRAINT "PK_SYS_DICT_DATA_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_DICT_DATA_ID";

-- 字典分组表
CREATE TABLE "SPECTRA"."SYS_DICT_ITEM"
(
    "ID"         NUMBER(19, 0)            NOT NULL,

    "PID"        NUMBER(19, 0),
    "NAME"       VARCHAR2(100)            NOT NULL,
    "CODE"       VARCHAR2(100)            NOT NULL,
    "STATE"      SMALLINT                 NOT NULL,
    "REMARK"     CLOB,
    "BUILTIN"    NUMBER(1, 0)  DEFAULT 0  NOT NULL,
    "HIDE"       NUMBER(1, 0)  DEFAULT 0  NOT NULL,

    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL,
    "DELETED"    TIMESTAMP WITH TIME ZONE,
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_DICT_ITEM IS '字典组表';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."PID" IS '父级ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."NAME" IS '字典名称';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."CODE" IS '字典编码';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."STATE" IS '字典状态';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."BUILTIN" IS '是否内置字段,为TRUE则不允许他进行修改删除操作';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."HIDE" IS '是否隐藏,为TRUE则前端不可直接进行修改删除等操作';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_DICT_ITEM."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_DICT_GROUP_ID" ON "SPECTRA"."SYS_DICT_ITEM" (ID);
ALTER TABLE "SPECTRA"."SYS_DICT_ITEM"
    ADD CONSTRAINT "PK_SYS_DICT_GROUP_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_DICT_GROUP_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_DICT_GROUP_CODE" ON "SPECTRA"."SYS_DICT_ITEM" ("CODE");
