-- 权限表
CREATE TABLE "SPECTRA"."SYS_AUTHORITY"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "PID"        NUMBER(19, 0),
    "NAME"       VARCHAR2(100) NOT NULL,
    "CODE"       VARCHAR2(100) NOT NULL,
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)  NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_AUTHORITY IS '权限表';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."PID" IS '父级ID,用于构建树形结构';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."NAME" IS '权限名称';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."CODE" IS '权限编码';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_AUTHORITY."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_AUTHORITY_ID" ON "SPECTRA"."SYS_AUTHORITY" (ID);
ALTER TABLE "SPECTRA"."SYS_AUTHORITY"
    ADD CONSTRAINT "PK_SYS_AUTHORITY_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_AUTHORITY_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_AUTHORITY_CODE" ON "SPECTRA"."SYS_AUTHORITY" ("CODE");

-- 系统配置表
CREATE TABLE "SPECTRA"."SYS_CONFIG"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "KEY"        VARCHAR2(100) NOT NULL,
    "VALUE"      VARCHAR2(100) NOT NULL,
    "REMARKS"    VARCHAR2(255),
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)  NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_CONFIG IS '系统配置表';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."VERSION" IS '乐观锁版本号,默认0';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."KEY" IS '配置key';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."VALUE" IS '配置VALUE';
COMMENT ON COLUMN SPECTRA.SYS_CONFIG."REMARKS" IS '备注说明';

CREATE UNIQUE INDEX "IDX_UK_SYS_CONFIG_ID" ON "SPECTRA"."SYS_CONFIG" (ID);
ALTER TABLE "SPECTRA"."SYS_CONFIG"
    ADD CONSTRAINT "PK_SYS_CONFIG_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_CONFIG_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_CONFIG_KEY" ON "SPECTRA"."SYS_CONFIG" ("KEY");

-- 字典数据表
CREATE TABLE "SPECTRA"."SYS_DICT_DATA"
(
    "ID"         NUMBER(19, 0)           NOT NULL,
    "GID"        NUMBER(19, 0)           NOT NULL,
    "LABEL"      VARCHAR2(100)           NOT NULL,
    "VALUE"      VARCHAR2(100)           NOT NULL,
    "SORT"       SMALLINT      DEFAULT 0 NOT NULL,
    "STATE"      SMALLINT                NOT NULL,
    "REMARK"     VARCHAR2(255),
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)            NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)            NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_DICT_DATA IS '字典数据表';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."GID" IS '字典组ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."LABEL" IS '标签';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."VALUE" IS '值';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."SORT" IS '排序';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."STATE" IS '状态';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_DICT_DATA."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_DICT_DATA_ID" ON "SPECTRA"."SYS_DICT_DATA" (ID);
ALTER TABLE "SPECTRA"."SYS_DICT_DATA"
    ADD CONSTRAINT "PK_SYS_DICT_DATA_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_DICT_DATA_ID";

-- 字典分组表
CREATE TABLE "SPECTRA"."SYS_DICT_GROUP"
(
    "ID"         NUMBER(19, 0)           NOT NULL,
    "PID"        NUMBER(19, 0),
    "NAME"       VARCHAR2(100)           NOT NULL,
    "CODE"       VARCHAR2(100)           NOT NULL,
    "STATE"      SMALLINT                NOT NULL,
    "REMARK"     CLOB,
    "BUILTIN"    NUMBER(1, 0)  DEFAULT 0 NOT NULL,
    "HIDE"       NUMBER(1, 0)  DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)            NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)            NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_DICT_GROUP IS '字典组表';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."PID" IS '父级ID';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."NAME" IS '字典名称';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."CODE" IS '字典编码';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."STATE" IS '字典状态';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."BUILTIN" IS '是否内置字段,为TRUE则不允许他进行修改删除操作';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."HIDE" IS '是否隐藏,为TRUE则前端不可直接进行修改删除等操作';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_DICT_GROUP."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_DICT_GROUP_ID" ON "SPECTRA"."SYS_DICT_GROUP" (ID);
ALTER TABLE "SPECTRA"."SYS_DICT_GROUP"
    ADD CONSTRAINT "PK_SYS_DICT_GROUP_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_DICT_GROUP_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_DICT_GROUP_CODE" ON "SPECTRA"."SYS_DICT_GROUP" ("CODE");

-- 菜单表
CREATE TABLE "SPECTRA"."SYS_MENU"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "NAME"       VARCHAR2(100) NOT NULL,
    "PID"        NUMBER(19, 0),
    "ICON"       VARCHAR2(100),
    "PATH"       VARCHAR2(255) NOT NULL,
    "COMPONENT"  VARCHAR2(100) NOT NULL,
    "LAYOUT"     VARCHAR2(100),
    "SORT"       INTEGER       DEFAULT 0,
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)  NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_MENU IS '菜单表';
COMMENT ON COLUMN SPECTRA.SYS_MENU."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_MENU."NAME" IS '名称';
COMMENT ON COLUMN SPECTRA.SYS_MENU."PID" IS '父级ID';
COMMENT ON COLUMN SPECTRA.SYS_MENU."ICON" IS '图标';
COMMENT ON COLUMN SPECTRA.SYS_MENU."PATH" IS '请求路径';
COMMENT ON COLUMN SPECTRA.SYS_MENU."COMPONENT" IS '组件路径,为空则使用布局组件';
COMMENT ON COLUMN SPECTRA.SYS_MENU."LAYOUT" IS '布局';
COMMENT ON COLUMN SPECTRA.SYS_MENU."SORT" IS '排序';
COMMENT ON COLUMN SPECTRA.SYS_MENU."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_MENU."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_MENU."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_MENU."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_MENU."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_MENU."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_MENU_ID" ON "SPECTRA"."SYS_MENU" (ID);
ALTER TABLE "SPECTRA"."SYS_MENU"
    ADD CONSTRAINT "PK_SYS_MENU_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_MENU_ID";

-- 操作日志表
CREATE TABLE "SPECTRA"."SYS_LOG"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "TYPE"       NUMBER(10),
    "EXPLAIN"    VARCHAR2(255),
    "STATUS"     SMALLINT,
    "IP"         VARCHAR2(15),
    "METHOD"     VARCHAR2(255),
    "URL"        VARCHAR2(255),
    "ARGS"       BLOB,
    "RESULT"     BLOB,
    "TIME_COST"  NUMBER(19, 0),
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)  NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_LOG IS '操作日志表';
COMMENT ON COLUMN SPECTRA.SYS_LOG."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_LOG."TYPE" IS '日志类型';
COMMENT ON COLUMN SPECTRA.SYS_LOG."EXPLAIN" IS '日志说明';
COMMENT ON COLUMN SPECTRA.SYS_LOG."STATUS" IS '请求状态';
COMMENT ON COLUMN SPECTRA.SYS_LOG."IP" IS '来源IP';
COMMENT ON COLUMN SPECTRA.SYS_LOG."METHOD" IS '请求方法';
COMMENT ON COLUMN SPECTRA.SYS_LOG."URL" IS '请求URL';
COMMENT ON COLUMN SPECTRA.SYS_LOG."ARGS" IS '请求参数';
COMMENT ON COLUMN SPECTRA.SYS_LOG."RESULT" IS '请求响应';
COMMENT ON COLUMN SPECTRA.SYS_LOG."TIME_COST" IS '耗时';
COMMENT ON COLUMN SPECTRA.SYS_LOG."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_LOG."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_LOG."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_LOG."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_LOG."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_LOG."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_LOG_ID" ON "SPECTRA"."SYS_LOG" (ID);
ALTER TABLE "SPECTRA"."SYS_LOG"
    ADD CONSTRAINT "PK_SYS_LOG_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_LOG_ID";

-- 组织机构表
CREATE TABLE "SPECTRA"."SYS_ORGANIZATION"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "PID"        NUMBER(19, 0),
    "NAME"       VARCHAR2(100) NOT NULL,
    "CODE"       VARCHAR2(100) NOT NULL,
    "TYPE"       SMALLINT,
    "PATH"       VARCHAR2(255),
    "REMARK"     VARCHAR2(255),
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)  NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_ORGANIZATION IS '组织机构表';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."PID" IS '上级ID';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."NAME" IS '名称';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."CODE" IS '编码';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."TYPE" IS '公司类型';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."PATH" IS '组织机构路径';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_ORGANIZATION."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_ORGANIZATION_ID" ON "SPECTRA"."SYS_ORGANIZATION" (ID);
ALTER TABLE "SPECTRA"."SYS_ORGANIZATION"
    ADD CONSTRAINT "PK_SYS_ORGANIZATION_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_ORGANIZATION_ID";

-- 关联表:角色-权限
CREATE TABLE "SPECTRA"."SYS_REL_ROLE_AUTHORITY"
(
    "ID"           NUMBER(19, 0) NOT NULL,
    "ROLE_ID"      NUMBER(19, 0) NOT NULL,
    "AUTHORITY_ID" NUMBER(19, 0) NOT NULL,
    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP(6),
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP(6),
    "DELETED"      TIMESTAMP(6),
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_REL_ROLE_AUTHORITY IS '角色表<->权限表';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."AUTHORITY_ID" IS '权限ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_AUTHORITY."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_REL_ROLE_AUTHORITY_ID" ON "SPECTRA"."SYS_REL_ROLE_AUTHORITY" (ID);
ALTER TABLE "SPECTRA"."SYS_REL_ROLE_AUTHORITY"
    ADD CONSTRAINT "PK_SYS_REL_ROLE_AUTHORITY_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_REL_ROLE_AUTHORITY_ID";

-- 关联表:角色到菜单
CREATE TABLE "SPECTRA"."SYS_REL_ROLE_MENU"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "ROLE_ID"    NUMBER(19, 0) NOT NULL,
    "MENU_ID"    NUMBER(19, 0) NOT NULL,
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6),
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_REL_ROLE_MENU IS '角色表<->菜单表';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."DELETED" IS '软删除标识';
COMMENT ON COLUMN SPECTRA.SYS_REL_ROLE_MENU."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_REL_ROLE_MENU_ID" ON "SPECTRA"."SYS_REL_ROLE_MENU" (ID);
ALTER TABLE "SPECTRA"."SYS_REL_ROLE_MENU"
    ADD CONSTRAINT "PK_SYS_REL_ROLE_MENU_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_REL_ROLE_MENU_ID";

-- 关联表:用户到角色
CREATE TABLE "SPECTRA"."SYS_REL_USER_ROLE"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "USER_ID"    NUMBER(19, 0) NOT NULL,
    "ROLE_ID"    NUMBER(19, 0) NOT NULL,
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6),
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_REL_USER_ROLE IS '用户表<->角色表';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."USER_ID" IS '用户ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_REL_USER_ROLE."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_REL_USER_ROLE_ID" ON "SPECTRA"."SYS_REL_USER_ROLE" (ID);
ALTER TABLE "SPECTRA"."SYS_REL_USER_ROLE"
    ADD CONSTRAINT "PK_SYS_REL_USER_ROLE_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_REL_USER_ROLE_ID";

-- 角色表
CREATE TABLE "SPECTRA"."SYS_ROLE"
(
    "ID"         NUMBER(19, 0) NOT NULL,
    "NAME"       VARCHAR2(100),
    "CODE"       VARCHAR2(100),
    "STATE"      NUMBER(1, 0)  DEFAULT 1,
    "SCOPE"      INT,
    "BUILTIN"    NUMBER(1, 0)  DEFAULT 1,
    "REMARK"     CLOB,
    "CREATED_BY" NUMBER(19, 0),
    "CREATED_AT" TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY" NUMBER(19, 0),
    "UPDATED_AT" TIMESTAMP(6)  NOT NULL,
    "DELETED"    TIMESTAMP(6),
    "VERSION"    NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_ROLE IS '角色表';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."NAME" IS '名称';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."CODE" IS '编码';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."STATE" IS '状态';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."SCOPE" IS '范围';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."BUILTIN" IS '是否内置';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."REMARK" IS '备注';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."DELETED" IS '是否删除';
COMMENT ON COLUMN SPECTRA.SYS_ROLE."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_ROLE_ID" ON "SPECTRA"."SYS_ROLE" (ID);
ALTER TABLE "SPECTRA"."SYS_ROLE"
    ADD CONSTRAINT "PK_SYS_ROLE_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_ROLE_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_ROLE_CODE" ON "SPECTRA"."SYS_ROLE" ("CODE");

-- 用户表
CREATE TABLE "SPECTRA"."SYS_USER"
(
    "ID"              NUMBER(19, 0) NOT NULL,
    "NAME"            VARCHAR2(100) NOT NULL,
    "EMAIL"           VARCHAR2(100) NOT NULL,
    "AVATAR"          VARCHAR2(255),
    "STATE"           NUMBER(5, 0),
    "ORGANIZATION_ID" NUMBER(19, 0),
    "PASSWORD"        VARCHAR2(60)  NOT NULL,
    "CREATED_BY"      NUMBER(19, 0),
    "CREATED_AT"      TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY"      NUMBER(19, 0),
    "UPDATED_AT"      TIMESTAMP(6)  NOT NULL,
    "DELETED"         TIMESTAMP(6),
    "VERSION"         NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_USER IS '用户表';
COMMENT ON COLUMN SPECTRA.SYS_USER."NAME" IS '姓名';
COMMENT ON COLUMN SPECTRA.SYS_USER."EMAIL" IS '邮箱';
COMMENT ON COLUMN SPECTRA.SYS_USER."AVATAR" IS '头像';
COMMENT ON COLUMN SPECTRA.SYS_USER."STATE" IS '状态 0为假,非0为真';
COMMENT ON COLUMN SPECTRA.SYS_USER."ORGANIZATION_ID" IS '组织机构ID';
COMMENT ON COLUMN SPECTRA.SYS_USER."PASSWORD" IS '密码';
COMMENT ON COLUMN SPECTRA.SYS_USER."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_USER."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_USER."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_USER."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_USER."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_USER."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_USER."VERSION" IS '乐观锁';

CREATE UNIQUE INDEX "IDX_UK_SYS_USER_ID" ON "SPECTRA"."SYS_USER" (ID);
ALTER TABLE "SPECTRA"."SYS_USER"
    ADD CONSTRAINT "PK_SYS_USER_ID" PRIMARY KEY (ID) USING INDEX "IDX_UK_SYS_USER_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_USER_NAME" ON "SPECTRA"."SYS_USER" ("NAME");
CREATE UNIQUE INDEX "SPECTRA"."IDX_UK_SYS_USER_EMAIL" ON "SPECTRA"."SYS_USER" ("EMAIL");

-- 文件上传信息
CREATE TABLE "SPECTRA"."SYS_FILE_INFO"
(
    "ID"           NUMBER(19, 0) NOT NULL,

    "FILE_NAME"    VARCHAR2(32)  NOT NULL,
    "ORIGIN_NAME"  VARCHAR2(50)  NOT NULL,
    "SUFFIX"       VARCHAR2(50)  NOT NULL,
    "PATH"         VARCHAR2(500) NOT NULL,
    "SIZE"         NUMBER(19, 0) NOT NULL,
    "HASH"         VARCHAR2(64),
    "STORAGE_TYPE" NUMBER(5, 0)  NOT NULL,

    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP(6)  NOT NULL,
    "DELETED"      TIMESTAMP(6),
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_FILE_INFO IS '文件上传信息';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."FILE_NAME" IS '生成的32位的文件名称';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."ORIGIN_NAME" IS '文件源名称';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."SUFFIX" IS '文件后缀';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."PATH" IS '文件存储位置';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."SIZE" IS '文件大小';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."HASH" IS '文件hash值';
COMMENT ON COLUMN SPECTRA.SYS_FILE_INFO."STORAGE_TYPE" IS '文件存储类型,';

CREATE UNIQUE INDEX "IDX_SYS_FILE_INFO_ID" ON "SPECTRA"."SYS_FILE_INFO" (ID);
ALTER TABLE "SPECTRA"."SYS_FILE_INFO"
    ADD CONSTRAINT "PK_SYS_FILE_INFO" PRIMARY KEY (ID) USING INDEX "IDX_SYS_FILE_INFO_ID";

-- 文件分片上传信息处理
CREATE TABLE "SPECTRA"."SYS_FILE_CHUNK"
(
    "ID"           NUMBER(19, 0) NOT NULL,

    "FILE_ID"       VARCHAR2(64)    NOT NULL,
    "CHUNK_INDEX"   NUMBER(10, 0)   NOT NULL,
    "TOTAL_CHUNKS"  NUMBER(10, 0)   NOT NULL,
    "CHUNK_PATH"    VARCHAR2(500)   NOT NULL,
    "CHUNK_SIZE"    NUMBER(19, 0)   NOT NULL,

    "CREATED_BY"   NUMBER(19, 0),
    "CREATED_AT"   TIMESTAMP(6)  NOT NULL,
    "UPDATED_BY"   NUMBER(19, 0),
    "UPDATED_AT"   TIMESTAMP(6)  NOT NULL,
    "DELETED"      TIMESTAMP(6),
    "VERSION"      NUMBER(19, 0) DEFAULT 0
);

COMMENT ON TABLE SPECTRA.SYS_FILE_CHUNK IS '文件上传信息';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."ID" IS '主键ID';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CREATED_BY" IS '创建人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CREATED_AT" IS '创建时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."UPDATED_BY" IS '最后更新人';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."UPDATED_AT" IS '最后更新时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."DELETED" IS '删除时间';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."VERSION" IS '乐观锁';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."FILE_ID" IS '文件唯一标识（如 SHA256 或 UUID）';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CHUNK_INDEX" IS '分片序号（从 0 开始）';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."TOTAL_CHUNKS" IS '总分片数（冗余，便于校验）';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CHUNK_PATH" IS '分片在磁盘/OSS 的存储路径或 Key';
COMMENT ON COLUMN SPECTRA.SYS_FILE_CHUNK."CHUNK_SIZE" IS '当前分片字节数';

CREATE UNIQUE INDEX "IDX_SYS_FILE_CHUNK_ID" ON "SPECTRA"."SYS_FILE_CHUNK" (ID);
ALTER TABLE "SPECTRA"."SYS_FILE_CHUNK"
    ADD CONSTRAINT "PK_SYS_FILE_CHUNK" PRIMARY KEY (ID) USING INDEX "IDX_SYS_FILE_CHUNK_ID";
CREATE UNIQUE INDEX "SPECTRA"."IDX_SYS_FILE_CHUNK_FILE_ID" ON "SPECTRA"."SYS_FILE_CHUNK" ("FILE_ID");
