<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.devops00.spectra</groupId>
        <artifactId>spectra-starter</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>spectra-ai-base</artifactId>

    <description>AI支持的基础包</description>

    <properties>
        <java.version>25</java.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <langchain4j.version>1.14.1-beta24</langchain4j.version>
    </properties>

    <dependencies>
        <!--<dependency>-->
        <!--    <groupId>dev.langchain4j</groupId>-->
        <!--    <artifactId>langchain4j-open-ai-spring-boot4-starter</artifactId>-->
        <!--    <version>${langchain4j.version}</version>-->
        <!--</dependency>-->
        <!--<dependency>-->
        <!--    <groupId>dev.langchain4j</groupId>-->
        <!--    <artifactId>langchain4j-spring-boot4-starter</artifactId>-->
        <!--    <version>${langchain4j.version}</version>-->
        <!--</dependency>-->

        <dependency>
            <groupId>io.agentscope</groupId>
            <artifactId>agentscope-spring-boot-starter</artifactId>
            <version>1.0.12</version>
            <exclusions>
                <exclusion>
                    <groupId>io.modelcontextprotocol.sdk</groupId>
                    <artifactId>mcp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.modelcontextprotocol.sdk</groupId>
            <artifactId>mcp</artifactId>
            <version>1.1.2</version>
        </dependency>
    </dependencies>

</project>