flowable:
  database-schema: spectra_workflow
  database-schema-update: false
  jpa-enabled: false
  process-definition-location-prefix: classpath*:/processes/
  async-executor-activate: true
  history-level: full
  eventregistry:
    enabled: false
  idm:
    enabled: false
  app:
    enabled: false
  dmn:
    enabled: false
  cmmn:
    enabled: false
