spectra:
  # 文件相关
  file:
    # 文件上传配置
    upload:
      # 本地存储
      local:
        # 上传文件的位置
        upload-dir: ${spectra.system.base-dir}/uploads
        # 上传文件的位置(临时存储位置)
        upload-temp-dir: ${spectra.system.base-dir}/temp
      # s3协议配置
      s3:
        endpoint: ${S3_ENDPOINT}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
        bucket: ${S3_BUCKET}
        region: ${S3_REGION}
      # 默认存储使用的bean类型
      default-storage: s3
