# 自己项目的配置
spectra:
  # 用户相关(admin123)
  user:
    default-password: ${DEFAULT_PASSWORD}
  # 系统配置
  system:
    # 基础文件夹位置,后续日志;文件上传保存等位置都要以这个位置为基础
    base-dir: files
    # 许可证配置,如果启用了许可证模块才会有效
    license:
      license-path: ${spectra.system.base-dir}/license.lic
      public-key: classpath:key/publicKey.pem
      private-key: classpath:key/privateKey.pem
      password: ${LICENSE_PASSWORD}
    # CORS配置
    cors:
      mapping: "/**"
      origin-patterns: "*"
      methods: "*"
      headers: "*"
      credentials: true
      max-age: 3600
  # 文件相关
  file:
    # 文件上传配置
    upload:
      # 上传文件的位置
      upload-dir: ${spectra.system.base-dir}/uploads
      # 上传文件的位置(临时存储位置)
      upload-temp-dir: ${spectra.system.base-dir}/temp
      # 文件允许的类型
      allowed-types:
        - jpeg
        - png
        - pdf
      # 文件验证的策略
      strategies:
        - io.github.yangxj96.spectra.core.configure.fileupload.strategy.impl.TikaValidationStrategy
        - io.github.yangxj96.spectra.core.configure.fileupload.strategy.impl.MimeValidationStrategy
        - io.github.yangxj96.spectra.core.configure.fileupload.strategy.impl.ExtensionValidationStrategy
        - io.github.yangxj96.spectra.core.configure.fileupload.strategy.impl.MagicNumberValidationStrategy
      # 分片文件大小
      chunk-size: 1048576
  # 验证码相关
  kaptcha:
    type: math
    verify: false
    duration: 1m
  # 安全相关
  security:
    token-expire: 7200
    whitelists:
      - "/common/kaptcha"
      - "/auth/login"
      - "/druid/**"
      - "/workflow/**"
# 服务器配置
server:
  port: 8888
  ssl:
    # key-store: classpath:ssl/keystore.p12
    key-store: ${spectra.system.base-dir}/ssl/keystore.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: ${SSL_TYPE}
    key-alias: ${SSL_ALIAS}
  servlet:
    context-path: /api
    session:
      cookie:
        name: JSESSIONID
        path: /
        same-site: none
        secure: true
        http-only: true
# spring 配置
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  config:
    # .env文件内是K=V的键值对符合properties的解析方式,
    # [.properties]是告诉他用properties的方式进行解析
    # [.yaml]是告诉他用.yaml的方式进行计息
    import: classpath:env.properties
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  application:
    name: spectra-framework-launch
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化连接池大小
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 连接时最大等待时间（单位：毫秒）
      max-wait: 60000
      test-while-idle: true
      # 配置多久进行一次检测，检测需要关闭的连接（单位：毫秒）
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在连接池中最小生存的时间（单位：毫秒）
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在连接池中最大生存的时间（单位：毫秒）
      max-evictable-idle-time-millis: 900000
      # 配置测试连接是否可用的查询 sql
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 配置监控后台访问路径
        url-pattern: /druid/*
        # 允许清空数据
        reset-enable: false
        login-username: sysadmin
        login-password: sysadmin
      filter:
        # 统计
        stat:
          enabled: true
          # 开启慢 sql 记录
          log-slow-sql: true
          # 若执行耗时大于 2s，则视为慢 sql
          slow-sql-millis: 2000
          # 合并SQL
          merge-sql: true
        # 防火墙
        wall:
          enabled: true
          db-type: oracle
          config:
            multi-statement-allow: true
            inited: true
  data:
    redis:
      url: redis://QuVsKppcWvwwX2Vv@127.0.0.1:6379/0
      timeout: 10s
      connect-timeout: 5s
      lettuce:
        pool:
          enabled: true
          max-idle: 10
          min-idle: 2
          max-active: 20
          max-wait: 5000ms
        shutdown-timeout: 100ms
  # 关闭他自带的用户
  security:
    user:
      name:
      password:
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yangxj96.spectra.**.entity.dto
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      # 开发过程中,不使用逻辑删除
      # logic-delete-field: deleted
      # logic-not-delete-value: "null"
      # logic-delete-value: "now()"
      schema: SPECTRA
# 日志配置
logging:
  group:
    spectra: >-
      io.github.yangxj96.spectra.core
    other: >-
      com.ulisesbocchio.jasyptspringboot.configuration,
      io.github.yangxj96.spectra.core.configure.mvc.filter,
      io.github.yangxj96.spectra.core.configure.mvc.advice,
      io.github.yangxj96.spectra.core.configure,
      io.github.yangxj96.spectra.core.listener.ulog
    mp: >-
      io.github.yangxj96.spectra.core.mapper.system.OperationLogMapper
  level:
    root: info
    other: error
    spectra: debug
    mp: error
  charset:
    console: utf-8
    file: UTF-8
# 健康检查
management:
  endpoints:
    web:
      exposure:
        # 暴露所有
        include: "*"
  endpoint:
    health:
      # 显示详情状态,开发环境可以用always,生产用never
      show-details: never
# 工作流配置
flowable:
  # 数据库确定
  database-schema: SPECTRA_WORKFLOW
  database-schema-update: true
  jpa-enabled: false
  # 流程定义
  process-definition-location-prefix: classpath*:/processes/
  async-executor-activate: true
  history-level: full
  # 下面是所有可选模块,都用不到
  # 事件注册模块
  eventregistry:
    enabled: false
  # 身份管理引擎
  idm:
    enabled: false
  # Flowable 的“应用元模型”
  app:
    enabled: false
  # 决策模型引擎
  dmn:
    enabled: false
  # 案例管理引擎
  cmmn:
    enabled: false
# XSS防范
mica:
  xss:
    # 是否开启
    enabled: true
    # 拦截的
    path-patterns: /**
    # 放行的
    path-exclude-patterns: