spectra:
  system:
    base-dir: files
  user:
    default-password: ${DEFAULT_PASSWORD}
  file:
    upload:
      upload-dir: ${spectra.system.base-dir}/uploads
      upload-temp-dir: ${spectra.system.base-dir}/temp
  kaptcha:
    type: math
    verify: false
server:
  port: ${SERVER_PORT:80}
  ssl:
    key-store: ${spectra.system.base-dir}/ssl/keystore.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: ${SSL_TYPE}
    key-alias: ${SSL_ALIAS}
  servlet:
    context-path: /api
    session:
      cookie:
        name: JSESSIONID
        path: /
        same-site: none
        secure: true
        http-only: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  application:
    name: spectra-admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      url: redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      timeout: 10s
      connect-timeout: 5s
      lettuce:
        pool:
          enabled: true
          max-idle: 10
          min-idle: 2
          max-active: 20
          max-wait: 5000ms
        shutdown-timeout: 100ms
  security:
    user:
      name:
      password:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yangxj96.spectra.**.entity.dto
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: "null"
      logic-delete-value: "now()"
      schema: SPECTRA
  configuration-properties:
    schema: domain_core
logging:
  group:
    spectra: >-
      io.github.yangxj96.spectra.core
  level:
    root: info
    spectra: error
  charset:
    console: utf-8
    file: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized
flowable:
  database-schema: domain_workflow
  database-schema-update: true
  jpa-enabled: false
  process-definition-location-prefix: classpath*:/processes/
  async-executor-activate: true
  history-level: full
  eventregistry:
    enabled: false
  idm:
    enabled: false
  app:
    enabled: false
  dmn:
    enabled: false
  cmmn:
    enabled: false
mica:
  xss:
    enabled: true
    path-patterns: /**
    path-exclude-patterns:
