langchain4j:
  open-ai:
    chat-model:
      base-url: ${AI_BASE_URL}
      api-key: ${AI_KEY}
      model-name: ${AI_MODEL}
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: ${AI_BASE_URL}
      api-key: ${AI_KEY}
      model-name: ${AI_MODEL}
spectra:
  ai:
    rag:
      api-key: ${RAG_KEY}
      base-url: ${RAG_BASE_URL}
      model-name: ${RAG_MODEL}