# 服务器配置
server:
  port: 8888
  servlet:
    context-path: /api
# spring 配置
spring:
  main:
    banner-mode: off
  application:
    name: spectra-framework-launch
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spectra_framework_db?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ENC(n1BUyCGo/Xt4HemeFS6BcAGNN+LAnp4MAXAI13ES+LZW9ah856rDm6GHxKZ+MrI5)
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 10
      password:
      timeout: 10s
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yangxj96.spectra.**.entity.dto
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: "null"
      logic-delete-value: "now()"
# 日志配置
logging:
  level:
    spectra: debug
  group:
    spectra: com.yangxj96.spectra
# Sa-Token 配置
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  active-timeout: 3000
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true
  is-print: false
  alone-redis:
    database: 11
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s
# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# 自己项目的配置
spectra:
  user:
    default-password: ENC(xhyePaPkX7s1niOK06ACFUMbg9GRXVELQ26LfOXId14jAJBXvUG1BPPe76fB5hRo)
  file:
    base-dir: spectra-files
    upload-dir: uploads
    upload:
      allowed-types:
        - jpeg
        - png
        - pdf
      strategies:
        - com.yangxj96.spectra.common.fileupload.strategy.impl.TikaValidationStrategy
